import React from 'react';
import { DecoOverlay } from '../lib/decoOverlay';
import { garmentFrame } from '../lib/garmentFrame';
import PersonalizationOverlay from '../lib/personalizationOverlay';

export const frozenMockCss = `.pp-frozen-mocks{width:100%;display:grid;gap:16px}.pp-frozen-mock{margin:0;border:1px solid #dce4e7;border-radius:8px;padding:12px;break-inside:avoid}.pp-frozen-sides{display:flex;gap:12px;justify-content:center}.pp-frozen-side{flex:1;max-width:230px;min-width:0;text-align:center}.pp-frozen-frame{position:relative;aspect-ratio:4/5;background:#eef2f4;overflow:hidden;border-radius:4px}.pp-frozen-frame>img:first-child{display:block;width:100%;height:100%;object-fit:contain}.pp-frozen-side small{display:block;margin-top:4px}.pp-frozen-mock figcaption{font-size:12px;line-height:1.5;margin-top:10px;overflow-wrap:anywhere}.pp-frozen-text{white-space:pre-wrap;text-transform:none;font-weight:700}.pp-frozen-status{display:block;color:#475569}.pp-frozen-missing{display:flex;align-items:center;justify-content:center;height:100%;padding:18px;color:#64748b}.pp-frozen-caption{font-size:11px;color:#64748b;margin:6px 0 0}@media print{.pp-frozen-mocks{display:block}.pp-frozen-mock{margin-bottom:12px}.pp-frozen-frame{height:245px;aspect-ratio:auto}.pp-frozen-side{max-width:196px}}`;

export default function FrozenMocks({ mocks = [] }) {
  if (!mocks.length) return null;
  return <div className="pp-frozen-mocks"><style>{frozenMockCss}</style>{mocks.map(mock => {
    const hasBack = !!mock.imageBack || !!mock.name || !!mock.number || mock.decorations.some(d => d.side === 'back');
    return <figure className="pp-frozen-mock" key={mock.id}><div className="pp-frozen-sides">{['front', ...(hasBack ? ['back'] : [])].map(side => {
      const image = side === 'front' ? mock.imageFront : mock.imageBack;
      const frame = garmentFrame(image, mock.decorations);
      return <div className="pp-frozen-side" key={side}><div className="pp-frozen-frame">{image ? <img src={frame.src} style={{objectFit:frame.fit}} alt={`Purchased ${side} garment reference`} crossOrigin="anonymous" loading="eager"/> : <div className="pp-frozen-missing">{side === 'back' ? 'Back image not supplied' : 'Garment image not supplied'}</div>}<DecoOverlay decorations={mock.decorations} colorName={mock.color} side={side}/>{side === 'back' && <PersonalizationOverlay takesName={!!mock.name} takesNumber={!!mock.number} sampleName={mock.name} sampleNumber={mock.number} decorations={mock.decorations} preserveCase/>}</div><small>{side === 'back' ? 'Back' : 'Front'}</small></div>;
    })}</div><figcaption><strong>{mock.size} · {mock.qty} garment{mock.qty === 1 ? '' : 's'}</strong>{mock.name && <div>Print name: <span className="pp-frozen-text">{mock.name}</span></div>}{mock.number && <div>Print number: <span className="pp-frozen-text">{mock.number}</span></div>}<span className="pp-frozen-status">{mock.approved ? 'Approved store setup · frozen at purchase' : 'Frozen purchased setup · approval pending'}</span>{mock.artworkVersions.map(v => <small key={`${v.code}:${v.version}`}>Artwork {v.code} · version {v.version}</small>)}{(mock.name || mock.number) && <p className="pp-frozen-caption">Text placement reference. Use the frozen production template for print font, color and dimensions.{mock.name && ` Name: ${mock.template.font || "font unspecified"} · ${mock.template.printColor || "color unspecified"} · ${mock.template.widthIn || "?"} × ${mock.template.heightIn || "?"} in · ${mock.template.placement || "placement unspecified"}.`}{mock.number && ` Number: ${mock.numberTemplate.font || "font unspecified"} · ${mock.numberTemplate.printColor || "color unspecified"} · ${mock.numberTemplate.widthIn || "?"} × ${mock.numberTemplate.heightIn || "?"} in · ${mock.numberTemplate.placement || "placement unspecified"}.`}</p>}</figcaption></figure>;
  })}</div>;
}
