import { safeUrl, groupPlayerOrders } from './model';
export const packetImageUrls = packet => [...new Set(packet.decorations.flatMap(d=>[...d.mocks.map(f=>f.url), d.storePreview?.image, ...(!d.storePreview?.baked?[d.storePreview?.art]:[])]).map(safeUrl).filter(Boolean))];
const esc = v => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const sizes = values => Object.entries(values || {}).map(([s, n]) => `${esc(s)}: <b>${esc(n)}</b>`).join(' · ');
const table = (headers, rows) => `<table><thead><tr>${headers.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`;
const row = cells => `<tr>${cells.map(c => `<td>${c}</td>`).join('')}</tr>`;
const note = n => `<div class="instruction"><b>${esc(n.scope)}${n.soId ? ' · ' + esc(n.soId) : ''}</b><p>${esc(n.text)}</p></div>`;
export function packetPrintHtml(packet, { onlineUrl = '', qrDataUrl = '', draft = true, generatedAt = new Date().toISOString() } = {}) {
  const p = packet;
  const link = safeUrl(onlineUrl);
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(p.store.name)} — Production Packet</title><style>
  @page{size:Letter;margin:.55in .5in .65in}*{box-sizing:border-box}body{font:11px/1.5 Arial,sans-serif;color:#152a3a;margin:0}h1{font-size:34px;line-height:1.15;margin:18px 0}h2{font-size:22px;color:#132f3b;border-bottom:2px solid #158575;padding-bottom:9px;break-after:avoid}h3{font-size:15px;margin:0 0 8px}p{white-space:pre-wrap;margin:6px 0}.eyebrow{font-size:10px;letter-spacing:2px;color:#16796e;text-transform:uppercase;font-weight:bold}.cover{padding:32px 10px 20px}.subtitle{font-size:16px;color:#5b6d7a}.stats{display:flex;gap:15px;margin:25px 0}.stat{padding:16px;background:#eef5f3;flex:1;border-radius:8px}.stat b{display:block;font-size:27px}.section{break-before:page}table{width:100%;border-collapse:collapse;margin:12px 0;table-layout:fixed}thead{display:table-header-group}th{background:#eaf2f1;text-align:left;font-size:10px;padding:8px}td{padding:8px;vertical-align:top;border-bottom:1px solid #dce4e7;overflow-wrap:anywhere}tr,.instruction,.deco{break-inside:avoid}.instruction{background:#f4f7f7;border-left:3px solid #178575;padding:10px 12px;margin:8px 0}.warning{background:#fff3df;border-left:3px solid #c47b14;padding:10px;margin:10px 0}.deco{border:1px solid #dce4e7;padding:15px;margin:14px 0;border-radius:8px}.mocks{display:flex;gap:12px;flex-wrap:wrap}.mocks img{width:45%;height:220px;object-fit:contain;border:1px solid #e6eded}a{color:#117567;overflow-wrap:anywhere}.muted{color:#627582}.qr{width:90px;height:90px}.details{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pill{font-size:10px;padding:4px 8px;background:#f0e7cc;display:inline-block}ul{padding-left:18px}.draft{color:#9a5200;font-weight:bold}small{font-size:9px}
  </style></head><body><div class="cover"><div class="eyebrow">National Sports Apparel · Production</div><h1>${esc(p.store.name)}</h1><div class="subtitle">Store production packet</div><p class="${draft ? 'draft' : 'muted'}">${draft ? 'DRAFT — NOT RELEASED FOR PRODUCTION' : 'Issued revision ' + esc(p.revisionId)}</p><p>${esc(new Date(generatedAt).toLocaleString('en-US'))} · ${esc(p.salesOrders.map(s => s.id).join(', '))}</p><div class="stats"><div class="stat"><b>${p.totals.garments}</b>Production garments</div><div class="stat"><b>${p.totals.players}</b>Players / recipients</div><div class="stat"><b>${p.decorations.length}</b>Decoration assignments</div></div><p>Delivery: ${esc(p.store.deliveryMode || 'Confirm with staff')}</p><p>${p.totals.unbatchedUnits} units awaiting a sales-order batch; excluded from production garment totals.</p>${link ? `<p><a href="${esc(link)}">Open current production packet and messages</a></p>${/^data:image\/png;base64,/.test(qrDataUrl) ? `<img class="qr" alt="Current packet QR" src="${qrDataUrl}">` : ''}<small>${esc(link)}</small>` : '<p class="muted">Create a recipient link to include shared online access.</p>'}<p class="muted">This PDF is a dated snapshot. Check the online page for changes before production.</p><h2>Production instructions</h2>${p.notes.filter(n => ['store', 'so'].includes(n.scope)).map(note).join('') || '<p>No shared store-wide instructions.</p>'}${p.issues.length ? `<div class="warning"><b>Needs attention</b><ul>${p.issues.map(i => `<li>${esc(i)}</li>`).join('')}</ul></div>` : '<p>Production checks passed at generation.</p>'}</div>
  <section class="section"><h2>Garments & quantities</h2>${table(['Garment / SO', 'Color', 'Sizes', 'Units', 'Decoration'], p.garments.map(g => row([`<b>${esc(g.sku)}</b><br>${esc(g.name)}<br><small>${esc(g.soId || 'Store orders · awaiting batch')}</small>`, esc(g.color), sizes(g.sizes), esc(g.units), g.undecorated ? 'Blank' : g.decorationIds.map(id => {const d=p.decorations.find(x=>x.id===id);return esc(d?.name)+' · '+esc(d?.position);}).join('<br>')]))) }${p.notes.filter(n => n.scope === 'garment').map(n => `<h3>${esc(p.garments.find(g => g.id === n.targetId)?.sku || n.targetId)}</h3>${note(n)}`).join('')}</section>
  <section class="section"><h2>Decoration & production mocks</h2>${p.decorations.map(d => `<article class="deco"><div class="eyebrow">${esc(d.soId || 'Store orders · awaiting batch')} · ${esc(d.sku)} · ${esc(d.color)}</div><h3>${esc(d.name)} — ${esc(d.position)}</h3><div class="details"><p>Method: ${esc(d.method)}<br>Size: ${esc(d.dimensions)}<br>Pantone / ink colors: ${esc(d.pantoneColors || (!d.threadColors ? d.colors : '') || 'Not specified')}<br>Thread colors: ${esc(d.threadColors || 'Not specified')}<br>Stitch count: ${esc(d.stitches || 'Not specified')}</p><p>Decorator: ${esc(d.decorator || 'Unassigned')}<br>Quantity: <b>${d.units}</b><br>Artwork: ${d.approved ? 'Approved' : 'Review required'}</p></div><p>${sizes(d.sizes)}</p><div class="mocks">${d.mocks.map(f => /\.(pdf)(\?|$)/i.test(f.url) ? `<p><a href="${esc(f.url)}">${esc(f.name)} (PDF proof)</a></p>` : `<img alt="${esc(d.sku)} production mock" src="${esc(f.url)}">`).join('') || (d.storePreview ? `<div style="position:relative;width:240px;margin:auto">${d.storePreview.image?`<img style="width:240px;height:auto;display:block" src="${esc(d.storePreview.image)}" alt="Garment">`:''}${!d.storePreview.baked&&d.storePreview.art?`<img style="${d.storePreview.image?`position:absolute;left:${d.storePreview.x}%;top:${d.storePreview.y}%;width:${d.storePreview.w}%;height:auto;background:transparent;border:0;transform:translate(-50%,-50%)`:'width:200px;height:auto'}" src="${esc(d.storePreview.art)}" alt="Store artwork">`:''}</div><p>Store reference · production mock approval pending</p>` : '<p class="draft">No garment mock available</p>')}</div>${p.notes.filter(n => n.targetId === d.id).map(note).join('')}<p>Personalization font: ${esc(d.personalization.font || '—')}</p>${d.personalization.names ? `<p>${esc(d.personalization.names)}</p>` : ''}${d.personalization.roster.length ? table(['Size','Name','Number','Qty'],d.personalization.roster.map(r=>row([esc(r.size),esc(r.name),esc(r.number),esc(r.qty)]))) : ''}<p>${d.productionFiles.map(f => `<a href="${esc(f.url)}">${esc(f.name)}</a>`).join(' · ')}</p></article>`).join('')}</section>
  <section class="section"><h2>Player report</h2><p class="muted">Current SO substitutions are reflected below. Unbatched lines are marked separately.</p>${groupPlayerOrders(p.players).map(group=>`<h3>Order #${esc(group.orderId)} · ${esc(group.units)} items</h3>${table(['Player', 'SO', 'Garment', 'Color / size', 'Qty'], group.rows.map(r => row([`<b>${esc(r.player)}</b>${r.number ? ' #'+esc(r.number) : ''}<br><small>${esc(r.orderId)}</small>`, esc(r.soId || 'UNBATCHED'), `${esc(r.sku)}<br>${esc(r.name)}${r.wasSku ? '<br><small>Was '+esc(r.wasSku)+'</small>' : ''}${r.verify ? '<br><b>VERIFY</b>' : ''}`, `${esc(r.color)} / ${esc(r.size)}`, esc(r.qty)])))}`).join('')}${p.notes.filter(n=>n.scope==='player').map(n=>`<h3>${esc(p.players.find(r=>r.id===n.targetId)?.player || n.targetId)}</h3>${note(n)}`).join('')}</section>
  <section class="section"><h2>Shared notes & messages</h2><p class="muted">Conversation is a dated record. Messages do not replace approved production instructions.</p>${p.notes.map(note).join('')}${p.messages.map(m => `<div class="instruction"><b>${esc(m.author)} · ${esc(m.soId)}</b> <span class="pill">${esc(m.kind)}${m.resolvedAt ? ' · resolved' : ''}</span><p class="muted">${esc(m.ts)}</p><p>${esc(m.text)}</p>${m.attachments.map(f=>`<p><a href="${esc(f.url)}">${esc(f.name)}</a></p>`).join('')}</div>`).join('') || '<p>No shared messages.</p>'}</section><section class="section"><h2>Changes & issues</h2>${p.changes.substitutions.map(s=>`<p>${esc(s.soId)}: ${esc(s.from)} → ${esc(s.to)}</p>`).join('')}${p.changes.sizeChanges.map(s=>`<p>${esc(s.soId)} ${esc(s.sku)}: ${esc(s.from)} → ${esc(s.to)}</p>`).join('')}${p.issues.map(i=>`<div class="warning">${esc(i)}</div>`).join('') || '<p>No unresolved production issues at this revision.</p>'}</section></body></html>`;
}
