import { safeUrl, groupPlayerOrders, humanizeProductionValue, isPersonalization, productionLabel } from './model';

export const packetImageUrls = packet => [...new Set(packet.decorations.flatMap(d=>[...d.mocks.map(f=>f.url), d.storePreview?.image, ...(!d.storePreview?.baked?[d.storePreview?.art]:[])]).map(safeUrl).filter(Boolean))];
const esc = v => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const sizes = values => Object.entries(values || {}).map(([s, n]) => `${esc(s)}: <b>${esc(n)}</b>`).join(' · ');
const table = (headers, rows) => `<table><thead><tr>${headers.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`;
const row = cells => `<tr>${cells.map(c => `<td>${c}</td>`).join('')}</tr>`;
const note = n => `<div class="instruction"><b>${esc(n.scope)}${n.soId ? ' · ' + esc(n.soId) : ''}</b><p>${esc(n.text)}</p></div>`;
const empty = value => esc(value || 'Not specified');
const files = values => values.map(f => `<a href="${esc(f.url)}">${esc(f.name)}</a>`).join(' · ');

function mockHtml(d) {
  if (d.mocks.length) return d.mocks.map(f => /\.(pdf)(\?|$)/i.test(f.url) ? `<p><a href="${esc(f.url)}">${esc(f.name)} (PDF proof)</a></p>` : `<img alt="${esc(d.sku)} production mock" src="${esc(f.url)}">`).join('');
  if (!d.storePreview) return '<p class="draft">No garment mock available</p>';
  return `<div class="store-preview">${d.storePreview.image?`<img class="garment" src="${esc(d.storePreview.image)}" alt="Garment">`:''}${!d.storePreview.baked&&d.storePreview.art?`<img class="${d.storePreview.image?'overlay':'art-only'}" style="${d.storePreview.image?`left:${d.storePreview.x}%;top:${d.storePreview.y}%;width:${d.storePreview.w}%`:''}" src="${esc(d.storePreview.art)}" alt="Store artwork">`:''}</div><p>Store reference · production mock approval pending</p>`;
}

function artCard(d,p) {
  const colorLabel=d.method==='embroidery'?'Thread colors':'Pantone / ink colors';
  const colorValue=d.method==='embroidery'?(d.threadColors||d.colors):(d.pantoneColors||d.colors);
  return `<article class="deco"><div class="eyebrow">${esc(d.soId || 'Store orders · awaiting batch')} · ${esc(d.sku)} · ${esc(d.color)}</div><h3>${esc(d.name)} — ${esc(d.position)}</h3><div class="quantity"><b>${esc(d.units)} garments</b><span>${sizes(d.sizes)}</span></div><div class="mocks">${mockHtml(d)}</div><div class="details"><p>Method: ${empty(humanizeProductionValue(d.method))}<br>Dimensions: ${empty(d.dimensions)}<br>${colorLabel}: ${empty(colorValue)}${d.method==='embroidery'?`<br>Stitch count: ${empty(d.stitches?Number(d.stitches).toLocaleString():'')}`:''}</p><p>Decorator: ${empty(d.decorator)}<br>Artwork: ${d.approved ? 'Approved' : 'Review required'}<br>Production files: ${files(d.productionFiles)||'None attached'}</p></div>${p.notes.filter(n => n.targetId === d.id).map(note).join('')}</article>`;
}

function personalizationCard(d,p) {
  const roster=d.personalization.roster||[];
  const rosterTable=roster.length?table(['Size',d.kind==='names'?'Print name':'Number','Qty'],roster.map(r=>row([esc(r.size||'—'),`<b>${esc(r.name||r.number||'—')}</b>`,esc(r.qty)]))):'<p>No per-player roster is saved; use the application quantity above.</p>';
  return `<article class="deco personal"><div class="eyebrow">Personalization · ${esc(d.soId || 'Store orders · awaiting batch')} · ${esc(d.sku)} · ${esc(d.color)}</div><h3>${esc(productionLabel(d))} — ${esc(d.position)}</h3><div class="quantity"><b>${esc(d.units)} applications</b><span>${sizes(d.sizes)}</span></div><div class="details"><p>Method: ${empty(humanizeProductionValue(d.method))}<br>${d.kind==='numbers'?`Number size: ${empty(d.dimensions)}<br>Font: ${empty(d.personalization.font)}<br>`:''}Print / thread color: ${empty(d.colors)}</p><p>Decorator: ${empty(d.decorator)}<br>Status: Ready for production</p></div><h4>Personalization roster</h4>${rosterTable}${p.notes.filter(n => n.targetId === d.id).map(note).join('')}</article>`;
}

export function packetPrintHtml(packet, { onlineUrl = '', qrDataUrl = '', draft = true, generatedAt = new Date().toISOString() } = {}) {
  const p = packet, link = safeUrl(onlineUrl), art=p.decorations.filter(d=>!isPersonalization(d)), personal=p.decorations.filter(isPersonalization), orders=groupPlayerOrders(p.players);
  const primary=/^#[0-9a-f]{6}$/i.test(p.store.primaryColor||'')?p.store.primaryColor:'#19333c', accent=/^#[0-9a-f]{6}$/i.test(p.store.accentColor||'')?p.store.accentColor:'#167b6e';
  const garmentRows=p.garments.map(g=>row([`<b>${esc(g.sku)}</b><br>${esc(g.name)}<br><small>${esc(g.soId || 'Store orders · awaiting batch')}</small>`,esc(g.color),sizes(g.sizes),`<b>${esc(g.units)}</b>`,g.undecorated?'Blank':g.decorationIds.map(id=>{const d=p.decorations.find(x=>x.id===id);return `${esc(productionLabel(d))} · ${esc(d?.position)}`;}).join('<br>')]));
  const playerBlocks=orders.map(group=>`<article class="order"><h3>Order #${esc(group.orderId)} · ${esc(group.recipient)} <span>${esc(group.units)} items</span></h3>${table(['Order recipient','Personalization','Garment','Color / size','Qty','SO'],group.rows.map(r=>row([esc(group.recipient),r.player!==group.recipient&&r.player!=='Unassigned'?`<b>${esc(r.player)}</b>${r.number?` #${esc(r.number)}`:''}`:(r.number?`#${esc(r.number)}`:'—'),`<b>${esc(r.sku)}</b><br>${esc(r.name)}`,`${esc(r.color)} / ${esc(r.size)}`,esc(r.qty),esc(r.soId||'Awaiting batch')])) )}</article>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(p.store.name)} — Production Packet</title><style>
  @page{size:Letter;margin:.55in .5in .65in}*{box-sizing:border-box}body{--primary:${primary};--accent:${accent};font:11px/1.5 Arial,sans-serif;color:#152a3a;margin:0}h1{font-size:34px;line-height:1.15;margin:12px 0}h2{font-size:22px;color:var(--primary);border-bottom:2px solid var(--accent);padding-bottom:9px;break-after:avoid}h3{font-size:15px;margin:0 0 8px}h4{margin:12px 0 4px}p{white-space:pre-wrap;margin:6px 0}.eyebrow{font-size:10px;letter-spacing:2px;color:var(--accent);text-transform:uppercase;font-weight:bold}.cover{padding:32px 10px 20px}.cover-head{display:flex;gap:18px;align-items:center}.store-logo{width:80px;height:80px;object-fit:contain;border:1px solid #dce4e7;border-radius:10px;padding:6px}.subtitle{font-size:16px;color:#5b6d7a}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:25px 0}.stat{padding:13px;background:#eef5f3;border-radius:8px}.stat b{display:block;font-size:24px}.section{break-before:page}table{width:100%;border-collapse:collapse;margin:12px 0;table-layout:fixed}thead{display:table-header-group}th{background:#eaf2f1;text-align:left;font-size:9px;padding:7px}td{padding:7px;vertical-align:top;border-bottom:1px solid #dce4e7;overflow-wrap:anywhere}tr,.instruction,.deco,.order{break-inside:avoid}.instruction{background:#f4f7f7;border-left:3px solid var(--accent);padding:10px 12px;margin:8px 0}.warning{background:#fff3df;border-left:3px solid #c47b14;padding:10px;margin:10px 0}.deco{border:1px solid #dce4e7;padding:15px;margin:14px 0;border-radius:8px}.deco.personal{border-top:4px solid var(--accent)}.quantity{display:flex;justify-content:space-between;background:#eef5f3;padding:10px;margin:10px 0;border-radius:6px}.mocks{display:flex;gap:12px;flex-wrap:wrap}.mocks>img{width:45%;height:220px;object-fit:contain;border:1px solid #e6eded}.store-preview{position:relative;width:240px;margin:auto}.store-preview .garment{width:240px;height:auto;display:block}.store-preview .overlay{position:absolute;height:auto;transform:translate(-50%,-50%);background:transparent;border:0}.store-preview .art-only{width:200px;height:auto}.details{display:grid;grid-template-columns:1fr 1fr;gap:8px}.order h3 span{float:right;font-size:11px;color:#627582}a{color:#117567;overflow-wrap:anywhere}.muted{color:#627582}.qr{width:90px;height:90px}.draft{color:#9a5200;font-weight:bold}small{font-size:9px}
  </style></head><body><div class="cover"><div class="cover-head">${p.store.logoUrl?`<img class="store-logo" src="${esc(p.store.logoUrl)}" alt="${esc(p.store.name)} logo">`:''}<div><div class="eyebrow">National Sports Apparel · Production</div><h1>${esc(p.store.name)}</h1><div class="subtitle">Store production packet</div></div></div><p class="${draft ? 'draft' : 'muted'}">${draft ? 'DRAFT — NOT RELEASED FOR PRODUCTION' : 'Issued revision ' + esc(p.revisionId)}</p><p>${esc(new Date(generatedAt).toLocaleString('en-US'))} · ${esc(p.salesOrders.map(s => s.id).join(', '))}</p><div class="stats"><div class="stat"><b>${p.totals.garments}</b>Garment units</div><div class="stat"><b>${p.totals.orders??orders.length}</b>Store orders</div><div class="stat"><b>${art.length}</b>Art placements</div><div class="stat"><b>${personal.length}</b>Personalization runs</div></div><p>Delivery: ${esc(p.store.deliveryMode || 'Confirm with staff')}</p><p>${p.totals.unbatchedUnits} units awaiting a sales-order batch.</p>${link ? `<p><a href="${esc(link)}">Open current production packet and messages</a></p>${/^data:image\/png;base64,/.test(qrDataUrl) ? `<img class="qr" alt="Current packet QR" src="${qrDataUrl}">` : ''}<small>${esc(link)}</small>` : '<p class="muted">Create a recipient link to include shared online access.</p>'}<p class="muted">This PDF is a dated snapshot. Check the online page for changes before production.</p><h2>Production instructions</h2>${p.notes.filter(n => ['store', 'so'].includes(n.scope)).map(note).join('') || '<p>No shared store-wide instructions.</p>'}${p.issues.length ? `<div class="warning"><b>Needs attention</b><ul>${p.issues.map(i => `<li>${esc(i)}</li>`).join('')}</ul></div>` : '<p>Production checks passed at generation.</p>'}</div>
  <section class="section"><h2>Garments & quantities</h2>${table(['Garment / SO','Color','Sizes','Units','Applications'],garmentRows)}${p.notes.filter(n => n.scope === 'garment').map(n => `<h3>${esc(p.garments.find(g => g.id === n.targetId)?.sku || n.targetId)}</h3>${note(n)}`).join('')}</section>
  <section class="section"><h2>Artwork & production mocks</h2>${art.map(d=>artCard(d,p)).join('')||'<p>No artwork placements in this packet.</p>'}</section>
  ${personal.length?`<section class="section"><h2>Player personalization</h2>${personal.map(d=>personalizationCard(d,p)).join('')}</section>`:''}
  <section class="section"><h2>Player report by order</h2>${playerBlocks||'<p>No player orders in this packet.</p>'}</section>
  <section class="section"><h2>Shared notes & SO conversation</h2>${p.notes.map(note).join('')||'<p>No shared production instructions.</p>'}${p.messages.map(m=>`<div class="instruction"><b>${esc(m.author)} · ${esc(m.soId)} · ${esc(m.kind)}</b><p>${esc(m.text)}</p></div>`).join('')||'<p>No shared SO messages.</p>'}<h2>Changes & unresolved issues</h2>${p.changes.substitutions.map(s=>`<p>${esc(s.soId)}: ${esc(s.from)} → ${esc(s.to)}</p>`).join('')}${p.changes.sizeChanges.map(s=>`<p>${esc(s.soId)} ${esc(s.sku)}: ${esc(s.from)} → ${esc(s.to)}</p>`).join('')}${p.issues.map(i=>`<div class="warning">${esc(i)}</div>`).join('')||'<p>No unresolved production issues at this revision.</p>'}</section></body></html>`;
}
