import React,{useState} from 'react';
export default function Shipping({packet,busy,historical,submit}) {
 const choices=packet.dpo?[packet.dpo]:(packet.dpos||[]);
 const [choice,setChoice]=useState(''),[carrier,setCarrier]=useState('ups'),[tracking,setTracking]=useState(''),[quantity,setQuantity]=useState(''),[destination,setDestination]=useState(''),[notes,setNotes]=useState(''),[notice,setNotice]=useState('');
 const [date,setDate]=useState(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;});
 const selected=choices.find(d=>`${d.soId}:${d.id}`===choice)||(choices.length===1?choices[0]:null);
 const history=(packet.shipments||[]).slice().sort((a,b)=>String(b.shipDate).localeCompare(String(a.shipDate)));
 return <div className="pp-columns"><section className="pp-card"><h2>Report a shipment</h2><p>Save tracking to the SO and notify its rep in the portal and by email for invoice review.</p>{historical?<p>Open the live packet to report a shipment.</p>:!choices.length?<p>No active decoration purchase order is available. Ask the SO team to assign a DPO first.</p>:<form className="pp-shipping-form" onSubmit={async e=>{e.preventDefault();setNotice('');const result=await submit({target_so_id:selected?.soId,shipment_dpo_id:selected?.id,carrier,tracking_number:tracking,ship_date:date,quantity,destination,notes,fingerprint:packet.fingerprint});if(result){setNotice(result.duplicate?'This shipment was already recorded. No duplicate alert was created.':'Tracking saved. The rep has a portal alert; their email is queued for delivery.');setTracking('');setQuantity('');setNotes('');}}}>
 <label>Sales order / DPO<select required value={selected?`${selected.soId}:${selected.id}`:''} onChange={e=>{setChoice(e.target.value);setQuantity('');}}><option value="">Choose DPO…</option>{choices.map(d=><option key={`${d.soId}:${d.id}`} value={`${d.soId}:${d.id}`}>{d.soId} · {d.number} · {d.vendor}</option>)}</select></label>
 <label>Destination<select required value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose destination…</option><option value="customer">Customer / delivery to club</option><option value="nsa">Returning to NSA</option></select></label>
 <div className="pp-form-row"><label>Carrier<select value={carrier} onChange={e=>setCarrier(e.target.value)}><option value="ups">UPS</option><option value="fedex">FedEx</option><option value="usps">USPS</option></select></label><label>Ship date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label></div>
 <label>Tracking number<input required minLength={6} maxLength={60} autoComplete="off" value={tracking} onChange={e=>setTracking(e.target.value)}/></label>
 <label>Garments in this shipment<input type="number" required min="1" max={selected?.coveredQuantity||undefined} step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label>
 {selected&&<small>{selected.coveredQuantity} garments assigned to this DPO. Enter only the quantity in this parcel; add each tracking number separately.</small>}
 <label>Shipment details<textarea maxLength={2000} placeholder="Items / sizes included, carton details, shortages or remaining garments…" value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 <p className="pp-muted">Partial shipments are supported. Reporting tracking does not mark the whole order complete or create an invoice. Corrections can be made by staff in SO Tracking.</p>
 <button disabled={busy||!selected}>Save shipment & notify rep</button></form>}{notice&&<p role="status">{notice}</p>}</section>
 <section className="pp-card"><h2>Shipment history</h2><p className="pp-muted">Tracking from the portal’s SO records. Updates refresh automatically.</p>{history.map((s,i)=><article className="pp-note" key={s.id||i}><strong>{s.soId} · {s.dpoNumber||'Shipment'}</strong><p>{s.quantity?`${s.quantity} garments · `:''}{s.destination==='nsa'?'Returning to NSA':'Customer delivery'} · {s.shipDate}</p><p>{s.carrier.toUpperCase()} · {s.trackingUrl?<a href={s.trackingUrl} target="_blank" rel="noreferrer">{s.trackingNumber} ↗</a>:s.trackingNumber}</p>{s.notes&&<p>{s.notes}</p>}</article>)}{!history.length&&<p>No shipments recorded yet.</p>}</section></div>;
}
