import React,{useState} from 'react';
import {WORKFLOW_LABELS,groupProductionRuns,packetForRun,personalizationCsv} from './workflow';
import {createProductionFileManifest,bundleProductionFiles} from './download';
import {humanizeProductionValue} from './model';
export const saveText=(text,name,type='text/csv;charset=utf-8')=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);};
export function JobSummary({packet}) {
 const dpos=packet.dpo?[packet.dpo]:packet.dpos||[];
 return <section className="pp-card"><h2>Decorator job brief</h2>{dpos.length?dpos.map(d=><div className="pp-job" key={`${d.soId}-${d.id}`}><h3>{d.vendor} · {d.number}</h3><dl><dt>Sales order</dt><dd>{d.soId}</dd><dt>Expected return</dt><dd>{d.dueDate||'Confirm with the SO team'}</dd><dt>Decorator contact</dt><dd>{d.email?<a href={`mailto:${d.email}`}>{d.email}</a>:'Not supplied'}</dd><dt>DPO quantity</dt><dd>{d.savedQuantity??'Not supplied'}{d.coveredQuantity!=null?` · ${d.coveredQuantity} garments on covered SO lines`:''}</dd></dl>{(d.warnings||[]).map((w,i)=><p key={i} className="pp-attention">{w}</p>)}{d.notes&&<div className="pp-instructions"><strong>DPO instructions</strong><p>{d.notes}</p></div>}{d.discrepancy&&<p role="alert" className="pp-attention">DPO quantity and covered garment quantity differ. Confirm the intended applications before starting.</p>}</div>):<p>No active DPO is assigned. Confirm the production destination with the SO team.</p>}<p className="pp-muted">The expected return is the decorator deadline. Garment arrival and the return address must be confirmed in shared instructions if they are not specified on the DPO.</p></section>;
}
export function ProductionRuns({packet,download,busy,review}) {
 const runs=groupProductionRuns(packet);
 return <section className="pp-card"><h2>Production runs</h2><p className="pp-muted">Matching artwork and setup specs are grouped together. Totals are decoration applications, not unique garments.</p>{runs.map(run=><details key={run.id}><summary>{run.name} · {humanizeProductionValue(run.method)} · {run.position} — {run.units} applications</summary><p>{run.dimensions||'Dimensions needed'} · {run.colors||'Colors needed'}</p><div className="pp-table"><table><thead><tr><th>SO / garment</th><th>Color</th><th>Sizes</th><th>Applications</th><th/></tr></thead><tbody>{run.decorations.map(d=><tr key={d.id}><td>{d.soId} · {d.sku}</td><td>{d.color}</td><td>{Object.entries(d.sizes||{}).map(([s,n])=>`${s}: ${n}`).join(' · ')}</td><td>{d.units}</td><td><button onClick={()=>review({section:'decorations',targetId:d.id})}>View mock & specs</button></td></tr>)}</tbody></table></div><button disabled={busy} onClick={()=>download(packetForRun(packet,run))}>Download this run PDF</button></details>)}{!runs.length&&<p>No artwork runs assigned.</p>}</section>;
}
export function WorkshopUpdate({packet,currentSo,setSo,submit,busy,historical}) {
 const [status,setStatus]=useState('received'),[quantity,setQuantity]=useState(''),[detail,setDetail]=useState(''),[photo,setPhoto]=useState(null),[photoError,setPhotoError]=useState('');
 const updates=packet.messages.filter(m=>m.metadata?.type==='production_update'&&(!packet.dpo||m.metadata.dpoId===packet.dpo.id));
 const latest=updates.filter(m=>m.soId===currentSo&&m.metadata.status!=='acknowledged').slice(-1)[0];
 const ack=updates.filter(m=>m.metadata.status==='acknowledged'&&m.metadata.fingerprint===packet.fingerprint&&m.soId===currentSo).slice(-1)[0];
 return <section className="pp-card"><h2>Shop updates</h2>{latest&&<p><strong>{WORKFLOW_LABELS[latest.metadata.status]}</strong> · {latest.metadata.quantity} of {latest.metadata.total} garments · {new Date(latest.ts).toLocaleString()}</p>}{ack&&<p className="pp-good">Current production version reviewed by {ack.author} · {new Date(ack.ts).toLocaleString()}</p>}{!historical&&<><p className="pp-muted">Updates are recorded in the SO’s existing Messages tab. Quantity is the total covered by this update, not an additional quantity. These updates do not release or edit the order.</p><div className="pp-form-row"><select aria-label="Update sales order" value={currentSo} onChange={e=>setSo(e.target.value)}>{packet.salesOrders.map(s=><option key={s.id}>{s.id}</option>)}</select><select aria-label="Production update" value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(WORKFLOW_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{status!=='acknowledged'&&<input type="number" min="0" step="1" aria-label="Garments covered by update" placeholder="Garment quantity" value={quantity} onChange={e=>setQuantity(e.target.value)}/>}</div><textarea aria-label="Production update details" value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Shortage details, first-piece notes, partial completion, or questions…"/><label>Photo (JPEG or PNG, up to 2 MB)<input type="file" accept="image/jpeg,image/png" onChange={e=>{const f=e.target.files?.[0];setPhotoError('');setPhoto(null);if(!f)return;if(f.size>2*1024*1024||!['image/jpeg','image/png'].includes(f.type)){setPhotoError('Choose a JPEG or PNG under 2 MB.');return;}const r=new FileReader();r.onload=()=>setPhoto({name:f.name,type:f.type,content:String(r.result).split(',')[1]});r.readAsDataURL(f);}}/></label>{photoError&&<p role="alert">{photoError}</p>}{photo&&<p>{photo.name} ready to attach.</p>}<button disabled={busy||!currentSo||!!photoError} onClick={async()=>{if(await submit({workflow_status:status,quantity,text:detail,photo,target_so_id:currentSo,fingerprint:packet.fingerprint})){setDetail('');setQuantity('');setPhoto(null);}}}>Save to SO conversation</button></>}</section>;
}
export function DownloadFiles({packet,onError}) {
 const [busy,setBusy]=useState(false),groups=createProductionFileManifest(packet);
 return <section className="pp-card"><h2>Production downloads</h2><div className="pp-actions"><button onClick={()=>saveText(personalizationCsv(packet),'personalization.csv')}>Personalization CSV</button><button disabled={busy||!Object.keys(groups).length} onClick={async()=>{setBusy(true);try{await bundleProductionFiles(packet);}catch(e){onError(e.message);}finally{setBusy(false);}}}>{busy?'Preparing files…':'Download production files ZIP'}</button></div><p className="pp-muted">CSV preserves the supplied names and numbers. When importing into a spreadsheet, keep print text as a text column to preserve leading zeros.</p>{Object.entries(groups).map(([group,files])=><details key={group}><summary>{group} · {files.length} files</summary><div className="pp-files">{files.map((f,i)=><a key={i} href={f.url} target="_blank" rel="noreferrer">{f.name}</a>)}</div></details>)}</section>;
}
