import { methodSetupError } from './methodReadiness.shared';
import { DecoOverlay } from '../lib/decoOverlay';
import PersonalizationOverlay from '../lib/personalizationOverlay';
import React, { useState } from 'react';
export const productionSetupError = (item, transfers = [], art = []) => {
  const methodError = methodSetupError(item, transfers, art);
  if (methodError) return methodError;
  return '';
};
export default function ProductionSetupReview({ item, stock, transfers, art, staffId, onSave, onClose }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const blocked = productionSetupError(item, transfers, art);
  const approve = async () => {
    if (blocked || !staffId) return setError(blocked || 'A signed-in staff identity is required for approval.');
    setBusy(true);
    try { const ok = await onSave(item.id, { production_approved_at: new Date().toISOString(), production_approved_by: String(staffId) }); if (ok !== false) onClose(); } finally { setBusy(false); }
  };
  return <div role="dialog" aria-label="Review exact production setup" className="card" style={{ padding: 20 }}><h3 style={{ marginTop: 0 }}>Review production setup · {item.display_name || stock?.name || item.sku}</h3><p style={{ fontSize: 13 }}>Blank: <b>{item.sku}</b> · {stock?.color || item.variant_label || 'Catalog color'} · Offered sizes: {(item.sizes_offered || stock?.available_sizes || []).join(', ') || 'Catalog size scale'}</p><div style={{ display: 'flex', gap: 16, marginBottom: 16 }}>
      {['front', ...((item.takes_name || item.takes_number || (item.decorations || []).some((d) => d.side === 'back')) ? ['back'] : [])].map((side) => {
        const image = side === 'front' ? item.image_url || stock?.image_front_url : item.image_back_url || stock?.image_back_url;
        return <figure key={side} style={{ margin: 0, width: 240 }}><div style={{ position: 'relative', aspectRatio: '4/5', background: '#f1f5f9', borderRadius: 8, overflow: 'hidden' }}>{image ? <img src={image} alt={`Exact ${side} garment mockup`} style={{ width: '100%', height: '100%', objectFit: 'contain', display: 'block' }} /> : <div style={{ padding: 24 }}>Back garment image not supplied</div>}<DecoOverlay decorations={item.decorations} side={side} colorName={stock?.color} />{side === 'back' && <PersonalizationOverlay takesName={item.takes_name} takesNumber={item.takes_number} decorations={item.decorations} />}</div><figcaption style={{ fontSize: 12, marginTop: 5 }}>{side === 'front' ? 'Front placement' : 'Back / personalized text placement reference'}</figcaption></figure>;
      })}
    </div><div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>{(item.decorations || []).filter((d) => d.art_url).map((d, i) => <figure key={i} style={{ margin: 0 }}><img src={d.art_url} alt={`Production logo at ${d.placement || d.side || 'front'}`} style={{ width: 120, height: 120, objectFit: 'contain', background: '#f8fafc' }} /><figcaption style={{ fontSize: 12 }}>{d.placement || d.side || 'front'} · {d.type || 'Library method'}{d.transfer_code && ` · ${d.transfer_code}`}</figcaption></figure>)}</div><ul>{[...(item.transfer_codes || []), ...(item.transfer_code ? [item.transfer_code] : [])].map((code) => { const t = transfers.find((row) => row.code === code); return <li key={code}>{t?.label || code} · {t?.width_in} × {t?.height_in} in · {t?.production_file?.name || 'Production file missing'} · {t?.application_method || 'heat_press'}</li>; })}</ul>{item.takes_name && <p style={{ fontSize: 13 }}>Name template (use the .ai template for exact font/color; the mock shows placement): {item.personalization_template?.font || 'Missing'} · {item.personalization_template?.print_color} · {item.personalization_template?.width_in} × {item.personalization_template?.height_in} in · {item.personalization_template?.placement} · {item.personalization_template?.production_file?.name || 'File missing'}</p>}{item.takes_number && <p style={{ fontSize: 13 }}>Numbers: {(item.num_transfer_sets || []).join(', ') || (item.personalization_template?.number_template ? `${item.personalization_template.number_template.font} · ${item.personalization_template.number_template.print_color} · ${item.personalization_template.number_template.width_in} × ${item.personalization_template.number_template.height_in} in · ${item.personalization_template.number_template.placement} · ${item.personalization_template.number_template.production_file?.name || 'File missing'}` : 'Custom number template missing')}</p>}{item.production_approved_at && <p style={{ fontSize: 12, color: '#15803d' }}>Approved {new Date(item.production_approved_at).toLocaleString()} by {item.production_approved_by}</p>}{(blocked || error) && <p role="alert" style={{ color: '#b91c1c', fontSize: 13 }}>{error || blocked}</p>}<button className="btn btn-primary" disabled={busy || !!blocked || !staffId} onClick={approve}>Save ready setup</button> <button className="btn btn-secondary" disabled={busy} onClick={onClose}>Close review</button></div>;
}
