// Executes the purchasing migration and adversarial scenarios in isolated PGlite.
// Requires optional @electric-sql/pglite in NODE_PATH; never connects to Supabase.
const fs=require('fs');const assert=require('assert');const {PGlite}=require('@electric-sql/pglite');
const root=require('path').resolve(__dirname,'../..')+'/';const read=f=>fs.readFileSync(root+f,'utf8');
(async()=>{const db=new PGlite();await db.exec(read('e2e/pipeline/seed.sql').split('-- Reference / seed data')[0].replace(/^\\.*$/gm,''));
await db.exec(`alter table so_items add column source_webstore_item_ids uuid[];alter table so_items add column recipe_snapshot jsonb;alter table webstore_order_items add column production_recipe jsonb;alter table webstores add column all_school_settings jsonb default '{}';alter table webstore_orders add column order_source text;create table product_inventory(product_id text,size text,quantity integer);create table app_state(id text primary key,value text,updated_at timestamptz);create table so_item_po_lines(id serial primary key,so_item_id integer,po_id text,vendor text,sizes jsonb,received jsonb default '{}',cancelled jsonb default '{}',shipments jsonb default '[]',status text,created_at text,memo text);create table so_item_pick_lines(so_item_id integer,sizes jsonb,status text);set app.is_staff='true';`);
await db.exec(read('supabase/migrations/00193_purchase_orders.sql'));await db.exec(read('supabase/migrations/00202_teamshop_auto_po.sql'));await db.exec(`alter table teamshop_auto_po_needs add column dismissed_at timestamptz;`);await db.exec(read('supabase/migrations/20261002184054_all_school_purchasing_runtime.sql'));
console.log('Purchasing migration executes');
const sid='10000000-0000-0000-0000-000000000001';const token='90000000-0000-0000-0000-000000000001';
await db.exec(`insert into webstores(id,slug,name,org_type,all_school_settings) values('${sid}','school','School','all_school','{"purchasing":{"enabled":true,"minimum_cents":20000}}');update teamshop_auto_po_settings set auto_submit_enabled=true where vendor='SanMar';insert into products(id,sku,name,color) values('P','PC61','Tee','Navy');insert into sales_orders(id,memo,status) values('SO-1','School','need_order'),('SO-2','School','need_order');insert into so_items(so_id,item_index,product_id,sku,name,color,sizes) values('SO-1',0,'P','PC61','Tee','Navy','{"M":50}'),('SO-2',0,'P','PC61','Tee','Navy','{"M":50}');insert into webstore_orders(store_id,status,order_source,so_id) values('${sid}','batched','all_school','SO-1'),('${sid}','batched','all_school','SO-2');insert into teamshop_auto_po_needs(so_id,so_item_id,product_id,sku,size,qty_ordered,qty_needed,vendor,unit_cost_cents,skip_reason) select so_id,id,'P','PC61','M',50,50,'SanMar',500,'all_school_pending' from so_items;insert into product_inventory values('P','M',40);insert into sales_orders(id,status) values('SO-NORMAL','need_order');insert into so_items(so_id,item_index,product_id,sku,sizes) values('SO-NORMAL',0,'P','PC61','{"M":10}');insert into so_item_pick_lines select id,'{"M":10}','pick' from so_items where so_id='SO-NORMAL';`);
const ship={companyName:'NSA',address1:'210 E Emerson Ave',address2:'Suite E',city:'Orange',region:'CA',postalCode:'92865',country:'US'};
const seedSources=async()=>db.exec(`insert into webstore_order_items(order_id,product_id,sku,size,qty,production_recipe) select wo.id,i.product_id,i.sku,sz.key,sz.value::integer,'{}'::jsonb from so_items i join webstore_orders wo on wo.so_id=i.so_id cross join lateral jsonb_each_text(i.sizes) sz where i.source_webstore_item_ids is null;update so_items i set recipe_snapshot='{}'::jsonb,source_webstore_item_ids=(select array_agg(li.id) from webstore_order_items li join webstore_orders wo on wo.id=li.order_id where wo.so_id=i.so_id and li.sku=i.sku) where i.source_webstore_item_ids is null and exists(select 1 from webstore_orders wo where wo.so_id=i.so_id);`);
const plan=async(so,key,reason,combine=false,policy='separate')=>{await seedSources();const ids=(await db.query('select id from teamshop_auto_po_needs where so_id=$1',[so])).rows.map(x=>x.id);return(await db.query('select plan_all_school_purchase($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) r',[sid,'SanMar',key,ids,reason,combine,policy,100000,'test',ship])).rows[0].r;};
let r=await plan('SO-1','eval1','evaluate');assert.equal(r.total_cents,10000);assert.equal((await db.query('select qty from all_school_house_reservations')).rows[0].qty,30);console.log('Stock reserved once; residual $100 after normal pick reservations');
r=await plan('SO-1','run1','minimum');assert.equal(r.reason,'below_minimum');assert.equal((await db.query('select count(*) n from purchase_orders')).rows[0].n,0);console.log('Threshold rechecked on residual cost');
r=await plan('SO-2','run2','minimum');assert.equal(r.purchase_order.totals_cents,25000);const dedicated=r.purchase_order;
await db.exec("update webstore_order_items set line_status='cancelled' where order_id=(select id from webstore_orders where so_id='SO-2')");assert.equal((await db.query('select claim_all_school_po_submission($1,$2) r',[dedicated.id,token])).rows[0].r.claimed,false);await db.exec("update webstore_order_items set line_status='pending';update purchase_orders set submission_state='pending';update sales_orders set status='cancelled' where id='SO-2'");console.log('Partial source-line cancellation rechecked before supplier submission');assert.equal((await db.query('select claim_all_school_po_submission($1,$2) r',[dedicated.id,token])).rows[0].r.claimed,false);await db.exec("update sales_orders set status='need_order' where id='SO-2';update purchase_orders set submission_state='pending'");console.log('Cancellation rechecked before dispatch');assert.equal((await db.query('select claim_all_school_po_submission($1,$2) r',[dedicated.id,token])).rows[0].r.claimed,true);assert.equal((await db.query('select claim_all_school_po_submission($1,$2) r',[dedicated.id,token])).rows[0].r.claimed,false);assert.equal((await db.query('select claim_all_school_vendor_request($1,$2,$3) r',[token,dedicated.po_number,'SanMar'])).rows[0].r.claimed,true);assert.equal((await db.query('select claim_all_school_vendor_request($1,$2,$3) r',[token,dedicated.po_number,'SanMar'])).rows[0].r.claimed,false);console.log('Dedicated external request token consumed once');
await db.query('select record_all_school_po_submission($1,$2,$3,$4,$5,$6)',[dedicated.id,token,'unknown',null,'timeout',[]]);assert.equal((await db.query('select claim_all_school_po_submission($1,$2) r',[dedicated.id,token])).rows[0].r.claimed,false);
await db.exec(`insert into app_state values('batch_pos','[{"id":"NORMAL","vendor_key":"sanmar","items":[{"sizes":{"M":1}}]}]',now())`);
r=await plan('SO-1','runweekly','weekly',true);assert.equal(r.combined_regular,true);let queue=(await db.query("select value from app_state where id='batch_pos'")).rows[0].value;assert.equal(JSON.parse(queue).length,2);await db.exec(`update app_state set value='[]' where id='batch_pos'`);queue=JSON.parse((await db.query("select value from app_state where id='batch_pos'")).rows[0].value);assert.equal(queue.length,1);console.log('Durable regular addition survives stale queue erase');
const aid=queue[0].all_school_allocation_id;const sourceLines=queue[0].items.flatMap(it=>Object.entries(it.sizes).map(([size,quantity])=>({sourceBatchId:queue[0].id,sourceItemIdx:it.item_idx,size,quantity})));assert.equal((await db.query('select claim_all_school_regular_batch($1,$2,$3,$4,$5,$6) r',['sanmar',[aid],token,'NSA 7000',[],ship])).rows[0].r.reason,'source_quantity_changed');assert.equal((await db.query('select claim_all_school_regular_batch($1,$2,$3,$4,$5,$6) r',['sanmar',[aid],token,'NSA 7000',sourceLines,{...ship,postalCode:'90210'}])).rows[0].r.reason,'destination_changed');console.log('Removed sources and destination changes rejected');await db.exec("update webstore_order_items set line_status='cancelled' where order_id=(select id from webstore_orders where so_id='SO-1')");assert.equal((await db.query('select claim_all_school_regular_batch($1,$2,$3,$4,$5,$6) r',['sanmar',[aid],token,'NSA 7000',sourceLines,ship])).rows[0].r.reason,'source_line_changed');await db.exec("update webstore_order_items set line_status='pending';");console.log('Partial source-line cancellation also blocks regular batch submission');const regular=(await db.query('select claim_all_school_regular_batch($1,$2,$3,$4,$5,$6) r',['sanmar',[aid],token,'NSA 7000',sourceLines,ship])).rows[0].r;assert.equal(regular.claimed,true);assert.equal((await db.query('select claim_all_school_regular_batch($1,$2,$3,$4,$5,$6) r',['sanmar',[aid],token,'NSA 7000',sourceLines,ship])).rows[0].r.claimed,false);assert.equal((await db.query('select claim_all_school_vendor_request($1,$2,$3) r',[token,regular.po_number,'SanMar'])).rows[0].r.claimed,true);assert.equal((await db.query('select claim_all_school_vendor_request($1,$2,$3) r',[token,regular.po_number,'SanMar'])).rows[0].r.claimed,false);await db.query('select finish_all_school_regular_batch($1,$2,$3,$4,$5)',[token,regular.po_number,'submitted','VENDOR-1',[]]);queue=JSON.parse((await db.query("select value from app_state where id='batch_pos'")).rows[0].value);assert.equal(queue.length,0);console.log('Regular claim, token replay protection, finish remove verified');
await db.exec(`insert into sales_orders(id,status) values('SO-3','need_order'),('SO-4','need_order');insert into so_items(so_id,item_index,product_id,sku,sizes) values('SO-3',0,'P','PC61','{"M":1}'),('SO-4',0,'P','PC61','{"M":1}');insert into webstore_orders(store_id,status,order_source,so_id) values('${sid}','batched','all_school','SO-3'),('${sid}','batched','all_school','SO-4');insert into teamshop_auto_po_needs(so_id,so_item_id,product_id,sku,size,qty_ordered,qty_needed,vendor,unit_cost_cents,skip_reason) select so_id,id,'P','PC61','M',1,1,'SanMar',500,'all_school_pending' from so_items where so_id in('SO-3','SO-4');update product_inventory set quantity=0;update app_state set value='[{"id":"NORMAL","vendor_key":"sanmar","items":[{"sizes":{"M":1}}]}]' where id='batch_pos';`);
r=await plan('SO-3','maxwait-batch','weekly',true);assert.equal(r.combined_regular,true);const promotedPo=r.purchase_order;queue=JSON.parse((await db.query("select value from app_state where id='batch_pos'")).rows[0].value);const staleAid=queue.find(e=>e.all_school_allocation_id).all_school_allocation_id;
assert.equal((await db.query('select promote_all_school_regular_purchase($1) r',[promotedPo.id])).rows[0].r.reason,'waiting');
await db.exec("update webstore_orders set created_at=now()-interval '8 days' where so_id='SO-3'");r=(await db.query('select promote_all_school_regular_purchase($1) r',[promotedPo.id])).rows[0].r;assert.equal(r.promoted,true);assert.equal(r.purchase_order.threshold_eval.combined_regular,false);queue=JSON.parse((await db.query("select value from app_state where id='batch_pos'")).rows[0].value);assert.equal(queue.length,1);assert.equal(queue[0].id,'NORMAL');assert.equal((await db.query('select claim_all_school_regular_batch($1,$2,$3,$4,$5,$6) r',['sanmar',[staleAid],token,'NSA 7001',[],ship])).rows[0].r.claimed,false);assert.equal((await db.query('select count(*) n from so_item_po_lines where po_id=$1',[promotedPo.po_number])).rows[0].n,1);assert.equal((await db.query('select claim_all_school_po_submission($1,$2) r',[promotedPo.id,token])).rows[0].r.claimed,true);console.log('Maximum wait promotes queued allocations atomically; stale browser cannot submit them');
await db.exec("update app_state set value='[]' where id='batch_pos'");r=await plan('SO-4','held-weekly','weekly',true,'hold');assert.equal(r.reason,'no_compatible_regular_batch');r=await plan('SO-4','maxwait-fallback','max_wait',true,'hold');assert.equal(r.combined_regular,false);assert.equal(r.purchase_order.totals_cents,500);console.log('Maximum wait overrides no-batch hold without bypassing claims');
await db.exec(`insert into sales_orders(id,status) values('SO-5','need_order');insert into so_items(so_id,item_index,product_id,sku,sizes) values('SO-5',0,'P','PC61','{"M":4}');insert into webstore_orders(store_id,status,order_source,so_id) values('${sid}','batched','all_school','SO-5');insert into teamshop_auto_po_needs(so_id,so_item_id,product_id,sku,size,qty_ordered,qty_needed,vendor,unit_cost_cents,skip_reason) select so_id,id,'P','PC61','M',4,4,'SanMar',500,'all_school_pending' from so_items where so_id='SO-5';update product_inventory set quantity=4;update sales_orders set status='complete' where id in('SO-1','SO-NORMAL');`);
r=await plan('SO-5','own-house','evaluate');assert.equal(r.reason,'covered');await db.exec(`insert into so_item_pick_lines select id,'{"M":4}','pulled' from so_items where so_id='SO-5';update product_inventory set quantity=0;`);r=await plan('SO-5','own-house-pulled','evaluate');assert.equal(r.reason,'covered');assert.equal((await db.query("select qty_on_hand from teamshop_auto_po_needs where so_id='SO-5'")).rows[0].qty_on_hand,4);console.log('Own physically pulled stock remains covered without a second purchase');
await db.close();})().catch(e=>{console.error(e);process.exitCode=1});
