// Isolated All School fulfillment, source integrity and DTF receipt SQL scenarios.
// Run with optional @electric-sql/pglite available in NODE_PATH; never connects to Supabase.
const fs=require('fs');
const assert=require('assert/strict');
const {PGlite}=require('@electric-sql/pglite');
const root=require('path').resolve(__dirname,'../..')+'/';
const read=f=>fs.readFileSync(root+f,'utf8');
const sid='10000000-0000-0000-0000-000000000001';
const wid=n=>'20000000-0000-0000-0000-'+String(n).padStart(12,'0');
const oid=n=>'30000000-0000-0000-0000-'+String(n).padStart(12,'0');
const iid=n=>'40000000-0000-0000-0000-'+String(n).padStart(12,'0');
(async()=>{
 const db=new PGlite();
 const seed=read('e2e/pipeline/seed.sql').split('-- Reference / seed data')[0].replace(/^\\.*$/gm,'');
 await db.exec(seed);
 await db.exec(`alter table webstore_orders add column order_source text; alter table webstore_products add column transfer_code text; alter table webstore_products add column image_url text; alter table webstore_transfers add column unit_cost numeric; alter table so_jobs add column digitizing_needed boolean; alter table so_jobs add column dtf_prints_status text; alter table so_jobs add column notes text; create table job_stage_events(id bigserial,so_id text,job_id text,event text,from_state jsonb,to_state jsonb,actor text,source text,payload jsonb);
 insert into team_members(id,name,role) values('REP','Rep','rep'); insert into customers(id,name,primary_rep_id) values('C','School','REP'); insert into products(id,sku,name,brand,color,retail_price,nsa_cost) values('P','PC61','Tee','Port','Navy',40,5);
 insert into webstores(id,slug,name,org_type,customer_id,delivery_mode) values('${sid}','school','School','all_school','C','ship_home'); set app.is_staff='true';`);
 await db.exec(read('supabase/migrations/20261002183605_all_school_store_foundation.sql'));
 await db.exec(read('supabase/migrations/20261002183729_all_school_order_conversion.sql'));
 console.log('Current foundation and conversion migrations executed successfully against repository e2e schema');
 async function createOrder(n,source='all_school') {await db.query(`insert into webstore_orders(id,store_id,status,order_source,subtotal,total) values($1,$2,'paid',$3,40,44)`,[oid(n),sid,source]);}
 async function createLine(n,order,recipe,over={}) {await db.query(`insert into webstore_order_items(id,order_id,product_id,sku,size,qty,unit_price,unit_fundraise,production_recipe,line_status) values($1,$2,'P','PC61','M',$3,$4,0,$5,$6)`,[iid(n),oid(order),over.qty??1,over.price??40,recipe,over.status??'pending']);}
 const recipe=(id,art)=>({webstore_product_id:wid(id),product_id:'P',sku:'PC61',decorations:art?[{art_id:art,type:'dtf',placement:'full_front',art_url:'https://example.com/'+art}]:[],transfer_codes:[],takes_name:false,takes_number:false,mock_approval:{approved:true}});
 await createOrder(1); await createLine(1,1,recipe(1,'soccer')); await createLine(2,1,recipe(2,'baseball'));
 const firstConversion=(await db.query('select create_all_school_sales_order($1) result',[oid(1)])).rows[0].result;
 assert.equal(firstConversion.items,2);assert.equal(firstConversion.jobs,2);
 console.log('PASS same blank different sport recipes keep distinct SO lines/jobs');
 console.log('Distinct recipe SO lines:',(await db.query('select item_index,recipe_snapshot->>\'webstore_product_id\' recipe_id,sizes from so_items order by item_index')).rows);
 console.log('Distinct recipe jobs:',(await db.query('select id,key,art_name,items from so_jobs order by id')).rows);
 assert.equal((await db.query('select create_all_school_sales_order($1) result',[oid(1)])).rows[0].result.replayed,true);
 console.log('PASS conversion replay');
 await db.exec(`insert into webstore_transfers(store_id,code,label,on_hand,unit_cost) values('${sid}','PATCH','Patch',2,5)`);
 const transferRecipe={...recipe(3),transfer_codes:['PATCH'],transfer_inventory:[{code:'PATCH',label:'Patch',unit_cost:5,decoration_type:'patch',application_method:'heat_press',width_in:4,height_in:4,production_file:{path:'school/patch.pdf'}}]};
 await createOrder(2,null); await createLine(3,2,transferRecipe);
 try {console.log('NULL source reserve:',(await db.query('select reserve_all_school_decorations($1) result',[oid(2)])).rows);} catch(e){console.log('NULL source reserve rejected:',e.message)}
 await createOrder(3); await createLine(4,3,transferRecipe);
 console.log('Reserve patch:',(await db.query('select reserve_all_school_decorations($1) result',[oid(3)])).rows);
 await db.query(`update webstore_order_items set line_status='refunded' where id=$1`,[iid(4)]);
 console.log('Partial refund allocations:',(await db.query('select status,required_qty,reserved_qty from all_school_decoration_allocations where order_id=$1',[oid(3)])).rows);
 try {console.log('Refunded conversion result:',(await db.query('select create_all_school_sales_order($1) result',[oid(3)])).rows)} catch(e){console.log('Refunded-only order conversion rejected:',e.message)}
 await createOrder(4); await createLine(5,4,transferRecipe);
 console.log('Consume once:',(await db.query('select consume_all_school_decorations($1) result',[oid(4)])).rows);
 console.log('Consume replay:',(await db.query('select consume_all_school_decorations($1) result',[oid(4)])).rows);
 console.log('Patch physical on_hand:',(await db.query("select on_hand from webstore_transfers where code='PATCH'")).rows);

 const job=(await db.query("select so_id,id from so_jobs where so_id='SO-1001' order by id limit 1")).rows[0];
 async function ready(j=job){return (await db.query('select all_school_materials_ready($1,$2) result',[j.so_id,j.id])).rows[0].result;}
 assert.equal((await ready()).ready,true);
 const source=(await db.query("select source_webstore_item_ids from so_items where so_id=$1 and item_index=(select (items->0->>'item_idx')::integer from so_jobs where so_id=$1 and id=$2)",[job.so_id,job.id])).rows[0].source_webstore_item_ids[0];
 await db.query("update webstore_order_items set qty=2 where id=$1",[source]);
 assert.equal((await ready()).reason,'source_quantity_changed');
 await db.query("update webstore_order_items set qty=1,line_status='refunded' where id=$1",[source]);
 assert.equal((await ready()).reason,'source_line_inactive');
 await db.query("update webstore_order_items set line_status='pending',production_recipe=production_recipe || '{\"changed\":true}'::jsonb where id=$1",[source]);
 assert.equal((await ready()).reason,'source_recipe_changed');
 await db.query("update webstore_order_items set production_recipe=production_recipe-'changed' where id=$1",[source]);
 await db.query("update webstore_orders set status='refunded' where id=$1",[oid(1)]);
 assert.equal((await ready()).reason,'source_order_not_paid');
 await db.query("update webstore_orders set status='batched' where id=$1",[oid(1)]);
 assert.equal((await ready()).ready,true);
 const dtfRecipe={...recipe(5),transfer_codes:['DTF'],transfer_inventory:[{code:'DTF',label:'DTF',decoration_type:'dtf',application_method:'heat_press',width_in:4,height_in:4,production_file:{bucket:'all-school-art',path:'dtf.ai'}}]};
 await db.query("insert into webstore_transfers(store_id,code,label,on_hand) values($1,'DTF','DTF',2)",[sid]);
 await createOrder(5);await createLine(6,5,dtfRecipe,{qty:2});
 const converted=(await db.query('select create_all_school_sales_order($1) result',[oid(5)])).rows[0].result;
 const dtfJob=(await db.query('select so_id,id from so_jobs where so_id=$1',[converted.so_id])).rows[0];
 assert.equal((await ready(dtfJob)).reason,'decoration_not_physically_consumed');
 await db.query('select consume_all_school_decorations($1)',[oid(5)]);
 assert.equal((await ready(dtfJob)).ready,true);
 assert.equal((await db.query('select dtf_prints_status from so_jobs where so_id=$1 and id=$2',[dtfJob.so_id,dtfJob.id])).rows[0].dtf_prints_status,'received');
 await db.query('select consume_all_school_decorations($1)',[oid(5)]);
 assert.equal((await db.query("select on_hand from webstore_transfers where code='DTF'")).rows[0].on_hand,0);
 await db.query('delete from all_school_decoration_allocations where order_id=$1',[oid(5)]);
 assert.equal((await ready(dtfJob)).reason,'decoration_not_physically_consumed');
 const nameRecipe={...recipe(6),takes_name:true,personalization_template:{font:'Varsity',print_color:'White',width_in:8,height_in:2,production_file:{bucket:'all-school-art',path:'names.ai'}}};
 await createOrder(6);await createLine(7,6,nameRecipe);
 await db.query("update webstore_order_items set player_name='STEVE' where id=$1",[iid(7)]);
 const named=(await db.query('select create_all_school_sales_order($1) result',[oid(6)])).rows[0].result;
 await db.query('select consume_all_school_decorations($1)',[oid(6)]);
 assert.equal((await db.query('select dtf_prints_status from so_jobs where so_id=$1',[named.so_id])).rows[0].dtf_prints_status,null);
 console.log('PASS materials RPC: paid source, source qty/recipe/cancellation, missing consumption, stocked receiving + replay, personalized still waiting');

 await db.exec(read('supabase/migrations/20261002184500_all_school_dtf_batches.sql'));
 await createOrder(7);await createLine(8,7,dtfRecipe,{qty:2});
 const short=(await db.query('select create_all_school_sales_order($1) result',[oid(7)])).rows[0].result;
 const shortJob=(await db.query('select so_id,id from so_jobs where so_id=$1',[short.so_id])).rows[0];
 const allocation=(await db.query('select id,required_qty,reserved_qty from all_school_decoration_allocations where order_id=$1',[oid(7)])).rows[0];
 const manifest={so_id:shortJob.so_id,job_id:shortJob.id,order_id:oid(7),transfer_code:'DTF',qty:2,allocation_shortfalls:[{id:allocation.id,qty:2}]};
 await db.query('insert into all_school_dtf_requests(store_id,so_id,job_id,supplier_id,qty,manifest) values($1,$2,$3,\'Astra Sport\',2,$4)',[sid,shortJob.so_id,shortJob.id,manifest]);
 const claimed=(await db.query('select claim_all_school_dtf_batch($1,$2,$3) result',[sid,'Astra Sport',{vendor:'Astra Sport',email:'configured@example.com'}])).rows[0].result;
 assert.equal(claimed.manifest.length,1);
 assert.equal((await db.query('select claim_all_school_dtf_batch($1,$2,$3) result',[sid,'Astra Sport',{}])).rows[0].result.replayed,true);
 await db.query("update all_school_dtf_batches set status='sent' where id=$1",[claimed.id]);
 assert.equal((await db.query('select receive_all_school_dtf_batch($1,$2,$3) result',[claimed.id,'REP','A1'])).rows[0].result.received,true);
 assert.equal((await db.query("select on_hand from webstore_transfers where code='DTF'")).rows[0].on_hand,2);
 assert.equal((await db.query('select reserved_qty from all_school_decoration_allocations where id=$1',[allocation.id])).rows[0].reserved_qty,2);
 assert.equal((await ready(shortJob)).reason,'decoration_not_physically_consumed');
 assert.equal((await db.query('select receive_all_school_dtf_batch($1,$2,$3) result',[claimed.id,'REP','A1'])).rows[0].result.replayed,true);
 assert.equal((await db.query("select on_hand from webstore_transfers where code='DTF'")).rows[0].on_hand,2);
 await db.query('select consume_all_school_decorations($1)',[oid(7)]);
 assert.equal((await ready(shortJob)).ready,true);
 assert.equal((await db.query("select on_hand from webstore_transfers where code='DTF'")).rows[0].on_hand,0);
 console.log('PASS DTF SQL: batch claim replay, supplier receipt + reserved quantities once, readiness waits physical pull, consume ready');
 for (const [n,method] of [[8,'sew_on'],[9,'heat_press_and_sew']]) {
   const frozen={...transferRecipe,webstore_product_id:wid(n),transfer_inventory:[{...transferRecipe.transfer_inventory[0],application_method:method,application_instructions:'Use purchased navy thread, edge stitch twice.'}]};
   await createOrder(n);await createLine(n+1,n,frozen);
   const convertedSew=(await db.query('select create_all_school_sales_order($1) result',[oid(n)])).rows[0].result;
   const sewing=(await db.query('select deco_type,art_name,art_status,prod_status,notes from so_jobs where so_id=$1',[convertedSew.so_id])).rows[0];
   assert.equal(sewing.deco_type,'patch');assert.equal(sewing.art_status,'needs_art');assert.equal(sewing.prod_status,'hold');
   assert.ok(sewing.art_name.includes(method.replaceAll('_',' ')));assert.ok(sewing.notes.includes('edge stitch twice'));
   assert.equal(Number((await db.query('select cost_each from so_item_decorations d join so_items i on i.id=d.so_item_id where i.so_id=$1',[convertedSew.so_id])).rows[0].cost_each),5);
 }
 console.log('PASS sewing stock: sew-on and heat+sew retain manual patch/needs_art/hold, frozen instructions, purchased stock cost');
 // Stocked numeric transfers are exact frozen parts, not custom number prints.
 const digits=[['8in','White'],['6in','Navy']].flatMap(([size,color])=>[1,2].map(digit=>({code:`${digit}|${size}|${color}`,kind:'number',digit,tsize:size,color,label:`Digit ${digit} ${size} ${color}`,unit_cost:2,decoration_type:'dtf',application_method:'heat_press',width_in:4,height_in:8,production_file:{bucket:'all-school-art',path:`digit-${digit}-${size}.ai`}})));
 for (const digit of digits) await db.query('insert into webstore_transfers(store_id,kind,code,label,on_hand,unit_cost) values($1,$2,$3,$4,$5,$6)',[sid,'number',digit.code,digit.label,digit.digit===1?5:20,2]);
 const digitRecipe={...recipe(10),takes_number:true,num_transfer_sets:['8in|White','6in|Navy'],transfer_inventory:digits};
 const demand=(await db.query('select * from all_school_transfer_demand($1,3,$2)',[digitRecipe,'11'])).rows;
 assert.deepEqual(demand.map(d=>d.required_qty),[6,6]);
 await createOrder(10);await createLine(11,10,digitRecipe,{qty:2});await createLine(12,10,digitRecipe);
 await db.query('update webstore_order_items set player_number=$2 where id=$1',[iid(11),'11']);
 await db.query('update webstore_order_items set player_number=$2 where id=$1',[iid(12),'12']);
 const digitConverted=(await db.query('select create_all_school_sales_order($1) result',[oid(10)])).rows[0].result;
 assert.equal(digitConverted.items,1);assert.equal(digitConverted.jobs,4);
 const digitAlloc=(await db.query('select transfer_code,sum(required_qty)::int required,sum(reserved_qty)::int reserved from all_school_decoration_allocations where order_id=$1 group by transfer_code order by transfer_code',[oid(10)])).rows;
 assert.deepEqual(digitAlloc.map(d=>d.required),[5,5,1,1]);
 const digitJobs=(await db.query('select so_id,id,total_units,deco_type,dtf_prints_status from so_jobs where so_id=$1',[digitConverted.so_id])).rows;
 assert.ok(digitJobs.every(j=>j.total_units===3&&j.deco_type==='dtf'));
 assert.equal((await db.query("select count(*)::int n from job_stage_events where so_id=$1 and payload->>'logo_ref' like 'numbers:%'",[digitConverted.so_id])).rows[0].n,0);
 assert.equal(Number((await db.query("select sum(d.cost_each)::numeric cost from so_item_decorations d join so_items i on i.id=d.so_item_id where i.so_id=$1",[digitConverted.so_id])).rows[0].cost),8);
 await db.query('select consume_all_school_decorations($1)',[oid(10)]);
 assert.equal((await ready(digitJobs[0])).ready,true);
 assert.equal((await db.query("select sum(on_hand)::int total from webstore_transfers where kind='number'")).rows[0].total,38);
 await db.query('select consume_all_school_decorations($1)',[oid(10)]);
 assert.equal((await db.query("select sum(on_hand)::int total from webstore_transfers where kind='number'")).rows[0].total,38);
 // Same digit counts in a different printed number still invalidate readiness.
 await db.query('update webstore_order_items set player_number=$2 where id=$1',[iid(12),'21']);
 assert.equal((await ready(digitJobs[0])).reason,'decoration_not_physically_consumed');
 await assert.rejects(db.query('select consume_all_school_decorations($1)',[oid(10)]),/NSA_CONSUMED_RECIPE_CHANGED/);
 await db.query('update webstore_order_items set player_number=$2 where id=$1',[iid(12),'12']);
 await createOrder(11);await createLine(13,11,digitRecipe,{qty:3});
 await db.query('update webstore_order_items set player_number=$2 where id=$1',[iid(13),'11']);
 const shortage=(await db.query('select reserve_all_school_decorations($1) result',[oid(11)])).rows[0].result;
 assert.equal(shortage.short_qty,12);
 await db.query('update webstore_order_items set qty=2 where id=$1',[iid(13)]);
 assert.deepEqual((await db.query('select required_qty from all_school_decoration_allocations where order_id=$1 order by transfer_code',[oid(11)])).rows.map(d=>d.required_qty),[4,4]);
 console.log('PASS numeric stock: repeated11+12,two sets,physical reservation and shortage counts,per-code jobs,cost,consume replay,text correction gate');
 const customRecipe={...recipe(12),takes_number:true,takes_name:true,personalization_template:{unit_cost:2.25,number_template:{unit_cost:2.75,width_in:10,height_in:6,placement:'Back',production_file:{path:'numbers.ai'}},font:'Varsity',print_color:'White',width_in:8,height_in:2,production_file:{path:'text.ai'}}};
 await createOrder(12);await createLine(14,12,customRecipe);
 await db.query('update webstore_order_items set player_number=$2,player_name=$3 where id=$1',[iid(14),'12','STEVE']);
 const custom=(await db.query('select create_all_school_sales_order($1) result',[oid(12)])).rows[0].result;
 const personalCosts=(await db.query('select kind,num_method,cost_each from so_item_decorations d join so_items i on i.id=d.so_item_id where i.so_id=$1 order by kind',[custom.so_id])).rows;
 assert.equal(personalCosts[0].cost_each,'2.25');assert.equal(personalCosts[1].cost_each,'2.75');assert.equal(personalCosts[1].num_method,'dtf');
 const unapproved={...dtfRecipe,webstore_product_id:wid(13),mock_approval:{approved:false}};
 await createOrder(13);await createLine(15,13,unapproved);
 const held=(await db.query('select create_all_school_sales_order($1) result',[oid(13)])).rows[0].result;
 assert.equal((await db.query('select art_status from so_jobs where so_id=$1',[held.so_id])).rows[0].art_status,'needs_art');
 console.log('PASS frozen personalization method/cost and unapproved setup stays held');
 await db.query('insert into webstore_orders(id,store_id,status,order_source,target_ship_days) values($1,$2,\'pending_payment\',\'all_school\',7)',[oid(14),sid]);
 await db.query('update webstore_orders set status=\'paid\' where id=$1',[oid(14)]);
 const target=(await db.query('select payment_received_at,ship_target_at from webstore_orders where id=$1',[oid(14)])).rows[0];
 assert.equal(new Date(target.ship_target_at)-new Date(target.payment_received_at),7*86400000);
 await db.query('update webstore_orders set status=\'batched\',payment_received_at=now()+interval \'30 days\',target_ship_days=90 where id=$1',[oid(14)]);
 const retryTarget=(await db.query('select payment_received_at,ship_target_at from webstore_orders where id=$1',[oid(14)])).rows[0];
 assert.deepEqual(retryTarget,target);
 console.log('PASS shipment target stamped on paid transition and unchanged by delayed batching');
 // Approve only the exact offering configuration. Receipt is not a spec edit.
 await db.query('insert into webstore_products(id,store_id,product_id,transfer_code,image_url,production_approved_at,production_approved_by) values($1,$2,\'P\',\'PATCH\',\'mock.png\',now(),\'REP\')',[wid(20),sid]);
 assert.equal((await db.query('select production_approved_at from webstore_products where id=$1',[wid(20)])).rows[0].production_approved_at,null);
 await db.query('update webstore_products set production_approved_at=now(),production_approved_by=\'REP\' where id=$1',[wid(20)]);
 await db.query('update webstore_transfers set on_hand=on_hand+1 where store_id=$1 and code=\'PATCH\'',[sid]);
 assert.ok((await db.query('select production_approved_at from webstore_products where id=$1',[wid(20)])).rows[0].production_approved_at);
 await db.query('insert into webstore_products(id,store_id,product_id,transfer_code) values($1,$2,\'P\',\'DTF\')',[wid(21),sid]);
 await db.query('update webstore_products set production_approved_at=now(),production_approved_by=\'REP\' where id=$1',[wid(21)]);
 await db.query('update webstore_transfers set application_instructions=\'new spec\' where store_id=$1 and code=\'PATCH\'',[sid]);
 assert.equal((await db.query('select production_approved_at from webstore_products where id=$1',[wid(20)])).rows[0].production_approved_at,null);
 assert.ok((await db.query('select production_approved_at from webstore_products where id=$1',[wid(21)])).rows[0].production_approved_at);
 await db.query('update webstore_products set production_approved_at=now(),production_approved_by=\'REP\' where id=$1',[wid(20)]);
 await db.query('update webstore_products set image_url=\'changed.png\' where id=$1',[wid(20)]);
 assert.equal((await db.query('select production_approved_at from webstore_products where id=$1',[wid(20)])).rows[0].production_approved_at,null);
 console.log('PASS production approval: copied insert clears approval,physical stock receipt preserves it,spec/mock edits clear only relevant offering');
 await db.close();
})().catch(e=>{console.error(e.message); process.exitCode=1});
