import { buildProductionPacket, packetChanges, safeUrl, groupPlayerOrders, playerItemCsv, artSpecs } from '../productionPacket/model';
import { packetPrintHtml, packetImageUrls } from '../productionPacket/print';
const fixture=()=>({store:{id:'store1',name:'Falcons'},orders:[{id:'o1',store_id:'store1',so_id:'SO-1',status:'paid',buyer_email:'PRIVATE'}],lines:[{id:'l1',order_id:'o1',sku:'A',name:'Shirt',color:'Navy',size:'M',qty:2,player_name:'Taylor',player_number:'8'}],salesOrders:[{id:'SO-1',webstore_id:'store1',production_notes:'PRIVATE NOTE',items:[{id:1,item_index:0,line_id:'line1',sku:'A',name:'Shirt',color:'Navy',sizes:{M:2},no_deco:true,decorations:[]}],art_files:[]}],notes:[]});
test('public projection excludes financial and buyer data and internal production notes',()=>{const p=buildProductionPacket(fixture());expect(JSON.stringify(p)).not.toContain('PRIVATE');expect(p.totals.garments).toBe(2);expect(p.players[0].player).toBe('Taylor');expect(p.ready).toBe(true);});
test('SO replacements update both garment totals and player rows',()=>{const f=fixture();f.salesOrders[0].items[0].sku='B';const p=buildProductionPacket(f);expect(p.garments[0].sku).toBe('B');expect(p.players[0].sku).toBe('B');expect(p.players[0].wasSku).toBe('A');});
test('quantity reduction blocks issue without guessing which player loses an item',()=>{const f=fixture();f.salesOrders[0].items[0].sizes.M=1;const p=buildProductionPacket(f);expect(p.totals.garments).toBe(1);expect(p.players.reduce((n,r)=>n+r.qty,0)).toBe(2);expect(p.ready).toBe(false);expect(p.issues.join(' ')).toMatch(/do not match/);});
test('multiple decorations do not double garment quantities',()=>{const f=fixture();f.salesOrders[0].items[0].decorations=[{kind:'art',art_file_id:'a',position:'Front'},{kind:'art',art_file_id:'b',position:'Back'}];const p=buildProductionPacket(f);expect(p.totals.garments).toBe(2);expect(p.decorations.map(d=>d.units)).toEqual([2,2]);expect(p.ready).toBe(false);});
test('cancelled and unbatched customer lines are handled separately',()=>{const f=fixture();f.orders.push({id:'o2',store_id:'store1',status:'paid'},{id:'o3',store_id:'store1',status:'cancelled'});f.lines.push({...f.lines[0],id:'l2',order_id:'o2',qty:3},{...f.lines[0],id:'l3',order_id:'o3',qty:20});const p=buildProductionPacket(f);expect(p.totals.unbatchedUnits).toBe(3);expect(p.players).toHaveLength(2);expect(p.totals.garments).toBe(5);expect(p.garments.filter(g=>g.unbatched)[0].units).toBe(3);});
test('SO scoped packet excludes other SOs, players, notes, and messages',()=>{const f=fixture();f.salesOrders.push({...f.salesOrders[0],id:'SO-2'});f.orders.push({id:'o2',store_id:'store1',so_id:'SO-2',status:'paid'});f.lines.push({...f.lines[0],id:'l2',order_id:'o2'});f.notes=[{id:'n2',so_id:'SO-2',scope:'so',text:'Other SO'}];f.messages=[{id:'m2',soId:'SO-2',text:'Other conversation'}];const p=buildProductionPacket({...f,soId:'SO-1'});expect(p.salesOrders).toHaveLength(1);expect(p.players).toHaveLength(1);expect(p.notes).toHaveLength(0);expect(p.messages).toHaveLength(0);});
test('changed instructions and quantities are visible in revision diff',()=>{const f=fixture(),a=buildProductionPacket(f);f.notes.push({id:'n',scope:'store',text:'Bag by player'});f.salesOrders[0].items[0].sizes.M=3;expect(packetChanges(a,buildProductionPacket(f)).join(' ')).toMatch(/2 → 3/);expect(packetChanges(a,buildProductionPacket(f)).join(' ')).toContain('Bag by player');});
test('cleared garment mocks do not fall back to older supplier/art proof',()=>{const f=fixture();f.salesOrders[0].items[0].decorations=[{kind:'art',art_file_id:'a'}];f.salesOrders[0].art_files=[{id:'a',status:'approved',item_mockups:{'A|Navy':[]},mockup_files:[{url:'https://res.cloudinary.com/example/old.png'}]}];const p=buildProductionPacket(f);expect(p.decorations[0].mocks).toEqual([]);expect(p.issues.join(' ')).toContain('mock missing');});
test('print is self-contained and escapes instructions, names, and message HTML',()=>{const f=fixture();f.notes=[{id:'n',scope:'store',text:'<script>alert(1)</script>'}];const p=buildProductionPacket(f);const html=packetPrintHtml(p);expect(html).not.toContain('<script>');expect(html).toContain('&lt;script&gt;');expect(html).toContain('Taylor');expect(html).toContain('DRAFT');expect(html).not.toContain('PRIVATE');});
test('reject unsafe external URLs',()=>{expect(safeUrl('javascript:alert(1)')).toBe('');expect(safeUrl('http://localhost')).toBe('');expect(safeUrl('https://user:pass@example.com')).toBe('');});
test('split designs use their actual per-size allocation',()=>{const f=fixture();f.salesOrders[0].items[0].sizes={M:8,L:4};f.salesOrders[0].items[0].decorations=[{kind:'art',split_group:'split',split_sizes:{M:3,L:1}}];const p=buildProductionPacket(f);expect(p.decorations[0].units).toBe(4);expect(p.decorations[0].sizes).toEqual({M:3,L:1});expect(p.totals.garments).toBe(12);});
test('name and number maps preserve personalization and applicable quantity',()=>{const f=fixture();f.salesOrders[0].items[0].decorations=[{kind:'numbers',roster:{M:['8','']}},{kind:'names',names:{M:['TAYLOR','']}}];const p=buildProductionPacket(f);expect(p.decorations.map(d=>d.units)).toEqual([1,1]);expect(p.decorations[0].personalization.roster[0].number).toBe('8');expect(p.decorations[1].personalization.roster[0].name).toBe('TAYLOR');});
test('removed instruction targets block issue instead of silently dropping instructions',()=>{const f=fixture();f.notes=[{id:'n1',scope:'garment',target_id:'deleted-line',text:'Do not substitute'}];const p=buildProductionPacket(f);expect(p.notes).toHaveLength(1);expect(p.ready).toBe(false);expect(p.issues.join(' ')).toContain('target no longer exists');});

test('unbatched orders use saved catalog decoration and store art without becoming production ready',()=>{const f=fixture();f.orders[0].so_id=null;f.salesOrders=[];f.catalog=[{id:'c',sku:'A',decorations:[{art_id:'art',placement:'left_chest',art_url:'https://example.com/logo.png'}],image_url:'https://example.com/shirt.png'}];f.store.store_art=[{id:'art',name:'Team crest',status:'approved',deco_type:'embroidery',prod_files:[{url:'https://example.com/file.dst'}]}];const p=buildProductionPacket(f);expect(p.garments[0]).toMatchObject({sku:'A',units:2,unbatched:true});expect(p.decorations[0]).toMatchObject({name:'Team crest',method:'embroidery',units:2,storePreview:{image:'https://example.com/shirt.png',art:'https://example.com/logo.png'}});expect(p.ready).toBe(false);});
test('order grouping retains multiple players and all matching order items, export remains item-level',()=>{const rows=[{orderKey:'a',orderId:'10',player:'Taylor',sku:'TEE',qty:1},{orderKey:'a',orderId:'10',player:'Jordan',sku:'HAT',qty:2},{orderKey:'b',orderId:'11',player:'Taylor',sku:'TEE',qty:1}];const groups=groupPlayerOrders(rows,'HAT');expect(groups).toHaveLength(1);expect(groups[0].rows).toHaveLength(2);expect(groups[0].units).toBe(3);expect(playerItemCsv(rows).split('\r\n')).toHaveLength(4);});

test('PDF allowlist includes both store mock layers but excludes unsafe and unused baked art',()=>{expect(packetImageUrls({decorations:[{mocks:[],storePreview:{image:'https://res.cloudinary.com/garment.png',art:'https://res.cloudinary.com/logo.png'}},{mocks:[],storePreview:{image:'javascript:bad',art:'https://res.cloudinary.com/baked.png',baked:true}}]})).toEqual(['https://res.cloudinary.com/garment.png','https://res.cloudinary.com/logo.png']);});
test('original art specs preserve placement dimensions, stitch count and selected thread colors',()=>{expect(artSpecs({deco_type:'embroidery',art_size:'10 x 4',art_sizes:{'Left chest':'3 x 2'},stitches:8450,thread_colors:'Red'}, {position:'Left chest'},{inks:['Madeira 1147','White']})).toEqual({dimensions:'3 x 2',stitches:8450,threadColors:'Madeira 1147, White',pantoneColors:''});expect(artSpecs({deco_type:'screen_print',ink_colors:'185C'}, {},null).pantoneColors).toBe('185C');});
