/* eslint-disable */
import React, { useEffect, useMemo, useState } from 'react';
import { useAppData } from './AppContext';
import { supabase } from './lib/supabase';
import { calcOrderMargin } from './pricing';
import { calcSOStatus, isCommissionRep } from './businessLogic';
import {
  receivablesDashboard, arCashForecast, customerExposureReport, completedUninvoicedOrdersReport, buildArSnapshotRows,
} from './lib/financeEngine';
import { buildBrandedEmailHtml, getBillingContacts, sendBrevoEmail } from './utils';

const NAVY='#192853', BLUE='#3056c0', RED='#962c32', GOOD='#167354', AMBER='#b26b12';
const INK='#1e293b', MUTED='#64748b', FAINT='#94a3b8', LINE='#e2e8f0', SURFACE='#f8fafc';
const FD="'Barlow Condensed','Arial Narrow',sans-serif";
const money=n=>'$'+Math.round(Number(n)||0).toLocaleString();
const moneyExact=n=>(Number(n)||0).toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2});
const pct=n=>((Number(n)||0)*100).toFixed(0)+'%';
const ymd=d=>{const x=d instanceof Date?d:new Date(d);return Number.isNaN(x.getTime())?'':x.toLocaleDateString('en-CA')};
const shortDate=d=>{if(!d)return'—';const x=new Date(d);return Number.isNaN(x.getTime())?'—':x.toLocaleDateString('en-US',{month:'short',day:'numeric',year:x.getFullYear()!==new Date().getFullYear()?'numeric':undefined})};
const shortDateTime=d=>{if(!d)return'—';const x=new Date(d);return Number.isNaN(x.getTime())?'—':x.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})};
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim());
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STATUS={
  needs_contact:'Needs contact',waiting_customer:'Waiting on customer',rep_action:'Rep action needed',
  accounting_followup:'Accounting follow-up',monitoring:'Monitoring',complete:'Complete',
};
const STATUS_COLOR={needs_contact:RED,waiting_customer:AMBER,rep_action:'#7c3aed',accounting_followup:BLUE,monitoring:MUTED,complete:GOOD};
const isManager=u=>['admin','super_admin','gm','accounting'].includes(u?.role);
const localKey='nsa_ar_workflows_v1';
const readLocal=()=>{try{return JSON.parse(localStorage.getItem(localKey)||'{}')}catch{return{}}};
const saveLocal=x=>{try{localStorage.setItem(localKey,JSON.stringify(x))}catch{}};
const card={background:'#fff',border:'1px solid '+LINE,borderRadius:10,padding:16,boxShadow:'0 1px 2px rgba(15,23,42,.04)'};
const th={padding:'8px 10px',borderBottom:'1px solid '+LINE,fontSize:10,textTransform:'uppercase',letterSpacing:.45,color:MUTED,textAlign:'right',whiteSpace:'nowrap'};
const td={padding:'9px 10px',borderBottom:'1px solid #eef2f7',fontSize:12,textAlign:'right',verticalAlign:'top',fontVariantNumeric:'tabular-nums'};
const btn=(active=false)=>({border:'1px solid '+(active?NAVY:LINE),borderRadius:7,background:active?NAVY:'#fff',color:active?'#fff':NAVY,padding:'6px 10px',fontWeight:700,fontSize:11,cursor:'pointer'});

function scopedAr(ar, repId) {
  if(!repId)return ar;
  const openInvoices=ar.openInvoices.filter(i=>i.repId===repId);
  const assumedHistorical=(ar.assumedHistorical||[]).filter(i=>i.repId===repId);
  const buckets={current:0,d1_30:0,d31_60:0,d61_90:0,d90plus:0};
  openInvoices.forEach(i=>{const k=i.daysPastDue<=0?'current':i.daysPastDue<=30?'d1_30':i.daysPastDue<=60?'d31_60':i.daysPastDue<=90?'d61_90':'d90plus';buckets[k]+=i.balance});
  const total=openInvoices.reduce((a,i)=>a+i.balance,0),pastDue=buckets.d1_30+buckets.d31_60+buckets.d61_90+buckets.d90plus;
  const accountRows=ar.accountRows.filter(r=>r.repId===repId);
  return {...ar,openInvoices,assumedHistorical,accountRows,accountsNeedingInfo:ar.accountsNeedingInfo.filter(r=>r.repId===repId),accountPayRows:ar.accountPayRows.filter(r=>r.repId===repId),repPayRows:ar.repPayRows.filter(r=>r.repId===repId),repRows:ar.repRows.filter(r=>r.repId===repId),aging:{buckets,total,count:openInvoices.length},kpis:{...ar.kpis,total,pastDue,pastDuePct:total?pastDue/total:0,d60plus:buckets.d61_90+buckets.d90plus,d90plus:buckets.d90plus,dueNext7:openInvoices.filter(i=>i.dueDate&&i.dueDate>=new Date()&&(i.dueDate-new Date())/86400000<=7).reduce((a,i)=>a+i.balance,0),noBillingExposure:accountRows.filter(r=>!r.billingEmail).reduce((a,r)=>a+r.total,0),assumedHistoryCount:assumedHistorical.length,assumedHistoryFaceValue:assumedHistorical.reduce((a,i)=>a+(i.faceValue||0),0)}};
}

function Metric({label,value,sub,color=NAVY,onClick}){
  return <div role={onClick?'button':undefined} tabIndex={onClick?0:undefined} onClick={onClick} onKeyDown={onClick?e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onClick()}}:undefined} style={{...card,flex:'1 1 155px',minWidth:150,padding:'12px 14px',borderTop:'3px solid '+color,cursor:onClick?'pointer':'default',outline:'none'}}><div style={{fontSize:10,fontWeight:800,color:MUTED,textTransform:'uppercase',letterSpacing:.55}}>{label}</div><div style={{fontFamily:FD,fontSize:28,lineHeight:1.05,fontWeight:800,color,marginTop:5}}>{value}</div><div style={{fontSize:10.5,color:onClick?BLUE:FAINT,marginTop:4,fontWeight:onClick?700:400}}>{sub}</div></div>;
}

function MiniTrend({label,current,previous,previousDate,color=NAVY}){
  const delta=previous==null?null:current-previous,p=previous?delta/previous:null;
  return <div style={{padding:'10px 12px',background:SURFACE,border:'1px solid '+LINE,borderRadius:8}}><div style={{fontSize:10,textTransform:'uppercase',fontWeight:800,color:MUTED}}>{label}</div><div style={{display:'flex',alignItems:'baseline',gap:8,marginTop:3}}><b style={{fontFamily:FD,fontSize:22,color}}>{money(current)}</b>{delta!=null&&<span style={{fontSize:10,fontWeight:800,color:delta<=0?GOOD:RED}}>{delta<=0?'▼ ':'▲ '}{money(Math.abs(delta))}{p!=null?' · '+pct(Math.abs(p)):''}</span>}</div><div style={{fontSize:9.5,color:FAINT}}>{previous==null?'Trend starts with today’s snapshot':'since '+shortDate(previousDate)}</div></div>;
}

export default function ARWorkspace({ mode='admin', scopeRepId=null }) {
  const app=useAppData();
  const {sos=[],invs=[],histInvs=[],cust=[],REPS=[],cu,msgs=[],setMsgs,assignedTodos=[],setAssignedTodos,nf,companyInfo,setSelC,setPg,setInvF,setESO,setESOC,_truncatedTables=new Set()}=app;
  const manager=isManager(cu);
  const effectiveRep=manager?(scopeRepId&&scopeRepId!=='all'?scopeRepId:null):cu?.id;
  const today=useMemo(()=>new Date(),[]);
  const salesReps=useMemo(()=>(REPS||[]).filter(isCommissionRep),[REPS]);
  const calcMargin=useMemo(()=>{const cache=new Map();return so=>{if(!cache.has(so.id))cache.set(so.id,calcOrderMargin(so,sos));return cache.get(so.id)}},[sos]);
  const allAr=useMemo(()=>receivablesDashboard({invs,histInvs,sos,customers:cust,reps:salesReps,staffReps:REPS,asOf:today}),[invs,histInvs,sos,cust,salesReps,REPS,today]);
  const ar=useMemo(()=>scopedAr(allAr,effectiveRep),[allAr,effectiveRep]);
  const allExposure=useMemo(()=>customerExposureReport({ar:allAr,sos,invs,histInvs,customers:cust,calcMargin,calcStatus:calcSOStatus}),[allAr,sos,invs,histInvs,cust,calcMargin]);
  const exposure=useMemo(()=>effectiveRep?allExposure.filter(r=>r.repId===effectiveRep):allExposure,[allExposure,effectiveRep]);
  const allCompletedOrders=useMemo(()=>completedUninvoicedOrdersReport({sos,invs,histInvs,customers:cust,calcMargin,calcStatus:calcSOStatus,asOf:today}),[sos,invs,histInvs,cust,calcMargin,today]);
  const completedOrders=useMemo(()=>effectiveRep?allCompletedOrders.filter(r=>r.repId===effectiveRep):allCompletedOrders,[allCompletedOrders,effectiveRep]);
  const forecast=useMemo(()=>arCashForecast({openInvoices:ar.openInvoices,accountPayRows:ar.accountPayRows,asOf:today}),[ar,today]);
  const [workflows,setWorkflows]=useState(readLocal);
  const [snapshots,setSnapshots]=useState([]);
  const [filter,setFilter]=useState('needs_action');
  const [search,setSearch]=useState('');
  const [selectedId,setSelectedId]=useState(null);
  const [drawerTab,setDrawerTab]=useState('timeline');
  const [chat,setChat]=useState('');
  const [taskTitle,setTaskTitle]=useState('');
  const [taskOwner,setTaskOwner]=useState('');
  const [taskDue,setTaskDue]=useState('');
  const [emailTo,setEmailTo]=useState('');
  const [emailSubject,setEmailSubject]=useState('');
  const [emailBody,setEmailBody]=useState('');
  const [emailSending,setEmailSending]=useState(false);
  const [inbound,setInbound]=useState([]);
  const [orderSearch,setOrderSearch]=useState('');

  useEffect(()=>{let alive=true;if(!supabase)return;supabase.from('ar_account_workflows').select('*').then(({data})=>{if(!alive||!data)return;setWorkflows(prev=>{const n={...prev};data.forEach(r=>{n[r.customer_id]=r});saveLocal(n);return n})});return()=>{alive=false}},[]);
  const scopeId=effectiveRep||'team';
  const snapshotRows=useMemo(()=>buildArSnapshotRows({ar:allAr,exposureRows:allExposure,reps:salesReps,asOf:today}),[allAr,allExposure,salesReps,today]);
  useEffect(()=>{let alive=true;if(!supabase)return;const rows=manager?snapshotRows:snapshotRows.filter(r=>r.scope_id===cu?.id);(async()=>{try{if(rows.length)await supabase.from('ar_daily_snapshots').upsert(rows,{onConflict:'as_of_date,scope_id'});const{data}=await supabase.from('ar_daily_snapshots').select('*').eq('scope_id',scopeId).order('as_of_date',{ascending:false}).limit(120);if(alive&&data)setSnapshots(data)}catch(_){}})();return()=>{alive=false}},[manager,scopeId,cu?.id,snapshotRows]);

  // A ready-to-bill order is operational work, not just a KPI. Seed one stable
  // rep TODO per order and let App's normal assigned_todos diff-save persist it.
  // Managers seed the whole team even while viewing one rep; reps can only seed
  // (and see) their own orders. Stable source/id values prevent duplicate tasks.
  useEffect(()=>{
    if(!setAssignedTodos||!cu?.id)return;
    const candidates=(manager?allCompletedOrders:completedOrders).filter(r=>r.repId);
    if(!candidates.length)return;
    setAssignedTodos(prev=>{
      const known=new Set((prev||[]).flatMap(t=>[t.source,t.id].filter(Boolean)));
      const now=new Date().toISOString();
      const fresh=candidates.filter(r=>!known.has('completed_uninvoiced:'+r.id)&&!known.has('todo-completed-uninvoiced-'+r.id)).map(r=>({
        id:'todo-completed-uninvoiced-'+r.id,
        title:'Invoice completed order — '+r.id,
        description:r.customerName+' has '+moneyExact(r.openToInvoice)+' remaining to invoice on completed sales order '+r.id+'. Open Financials → Receivables → Completed, Uninvoiced, verify the order, and create or correct the invoice.',
        created_by:cu.id,assigned_to:r.repId,so_id:r.id,customer_id:r.customerId,
        priority:1,status:'open',due_date:ymd(today),source:'completed_uninvoiced:'+r.id,
        created_at:now,updated_at:now,comments:[],
      }));
      return fresh.length?[...fresh,...prev]:prev;
    });
  },[manager,allCompletedOrders,completedOrders,setAssignedTodos,cu?.id,today]);

  const infoById=useMemo(()=>new Map(allAr.accountsNeedingInfo.map(r=>[r.customerId,r])),[allAr]);
  const arById=useMemo(()=>new Map(ar.accountRows.map(r=>[r.customerId,r])),[ar]);
  const workRows=useMemo(()=>{
    const map=new Map();
    const rowKey=r=>r.customerId||'raw:'+r.name;
    exposure.forEach(r=>map.set(rowKey(r),{...r}));
    ar.accountsNeedingInfo.forEach(r=>{const key=rowKey(r),old=map.get(key)||{customerId:r.customerId,name:r.name,repId:r.repId,openAR:r.exposure||0,pastDue:r.pastDue||0,completedUninvoiced:0,openOrderValue:0,totalExposure:r.exposure||0};map.set(key,{...old,issues:r.issues,billingEmail:r.billingEmail,coachEmail:r.coachEmail})});
    ar.accountRows.forEach(r=>{const key=rowKey(r),old=map.get(key)||{customerId:r.customerId,name:r.name,repId:r.repId,completedUninvoiced:0,openOrderValue:0,totalExposure:r.total};map.set(key,{...old,openAR:r.total,pastDue:r.pastDue,d60plus:r.d60plus,d90plus:r.d90plus,oldestDays:r.oldestDays,invoiceCount:r.invoiceCount,billingEmail:r.billingEmail,coachEmail:r.coachEmail,issues:infoById.get(r.customerId)?.issues||[]})});
    return [...map.values()].map(r=>({...r,workflow:workflows[r.customerId]||null}));
  },[exposure,ar,infoById,workflows]);
  const visibleRows=useMemo(()=>workRows.filter(r=>{
    const q=search.trim().toLowerCase();if(q&&!((r.name||'')+' '+(r.customerId||'')).toLowerCase().includes(q))return false;
    const w=r.workflow||{};
    if(filter==='past_due')return r.pastDue>0;
    if(filter==='60plus')return r.d60plus>0;
    if(filter==='uninvoiced')return r.completedUninvoiced>0;
    if(filter==='data')return (r.issues||[]).length>0;
    if(filter==='needs_action'){const due=w.next_action_date&&w.next_action_date<=ymd(today);return !w.status||w.status==='needs_contact'||w.status==='rep_action'||w.status==='accounting_followup'||due}
    return true;
  }).sort((a,b)=>{const ad=a.workflow?.next_action_date||'9999',bd=b.workflow?.next_action_date||'9999';if(ad!==bd)return ad.localeCompare(bd);return(b.pastDue-a.pastDue)||(b.totalExposure-a.totalExposure)}),[workRows,filter,search,today]);

  // Never resolve a null selection. Unlinked historical invoices can produce
  // rows with customerId=null; matching those on first render opened a random
  // account drawer and pulled every unlinked task into its timeline.
  const selected=selectedId?workRows.find(r=>r.customerId===selectedId)||null:null;
  const customer=cust.find(c=>c.id===selectedId)||null;
  const selectedAr=selectedId?arById.get(selectedId):null;
  const workflow=selectedId?(workflows[selectedId]||{}):{};
  const rep=REPS.find(r=>r.id===selected?.repId);
  const owner=REPS.find(r=>r.id===workflow.collection_owner_id);
  const accountMessages=useMemo(()=>msgs.filter(m=>m.entity_type==='customer'&&m.entity_id===selectedId).sort((a,b)=>new Date(b.ts)-new Date(a.ts)),[msgs,selectedId]);
  const accountTasks=useMemo(()=>assignedTodos.filter(t=>t.customer_id===selectedId).sort((a,b)=>(a.status==='open'?0:1)-(b.status==='open'?0:1)||String(a.due_date||'9999').localeCompare(String(b.due_date||'9999'))),[assignedTodos,selectedId]);

  useEffect(()=>{if(!selectedId||!setMsgs||!cu?.id)return;setMsgs(prev=>{let changed=false;const n=prev.map(m=>{if(m.entity_type==='customer'&&m.entity_id===selectedId&&!(m.read_by||[]).includes(cu.id)){changed=true;return{...m,read_by:[...(m.read_by||[]),cu.id]}}return m});return changed?n:prev})},[selectedId,cu?.id]);
  useEffect(()=>{let alive=true;setInbound([]);if(!selectedId||!supabase)return;supabase.from('ai_inbox_messages').select('id,subject,sender_email,sender_name,received_at,text_body,snippet,customer_id').eq('customer_id',selectedId).order('received_at',{ascending:false}).limit(50).then(({data})=>{if(alive&&data)setInbound(data)});return()=>{alive=false}},[selectedId]);
  useEffect(()=>{if(!selected||!customer)return;const billing=getBillingContacts(customer,cust).filter(c=>validEmail(c.email));const fallback=(customer.contacts||[]).filter(c=>validEmail(c.email));const to=(billing[0]||fallback[0])?.email||'';setEmailTo(to);setEmailSubject('Account balance follow-up — '+selected.name);setEmailBody('Hi there,\n\nWe are following up on the '+moneyExact(selected.openAR||0)+' open balance on your account. Please let us know if you need invoice copies or any additional information from us.\n\nThank you,\n'+(cu?.name||'NSA Accounting'));setTaskOwner(selected.repId||cu?.id||'');setTaskDue('');setTaskTitle('');setChat('');setDrawerTab('timeline')},[selectedId]);

  const saveWorkflow=(patch)=>{if(!selectedId)return;const now=new Date().toISOString();const row={customer_id:selectedId,collection_owner_id:workflow.collection_owner_id||null,status:workflow.status||'needs_contact',next_action_date:workflow.next_action_date||null,last_contacted_at:workflow.last_contacted_at||null,notes:workflow.notes||null,updated_by:cu?.id||null,updated_at:now,...patch};setWorkflows(prev=>{const n={...prev,[selectedId]:row};saveLocal(n);return n});if(supabase)supabase.from('ar_account_workflows').upsert(row,{onConflict:'customer_id'}).then(({error})=>{if(error)nf?.('AR workflow saved locally; cloud sync is unavailable.','warn')})};
  const postChat=()=>{const text=chat.trim();if(!text||!selectedId)return;const tagged=[selected?.repId,workflow.collection_owner_id].filter(id=>id&&id!==cu?.id);const msg={id:'m'+Date.now(),so_id:null,author_id:cu?.id,text,ts:new Date().toLocaleString(),read_by:[cu?.id].filter(Boolean),dept:'accounting',tagged_members:[...new Set(tagged)],entity_type:'customer',entity_id:selectedId};setMsgs?.(prev=>[...prev,msg]);setChat('');nf?.('Posted to the account AR conversation.','success')};
  const addTask=()=>{if(!taskTitle.trim()||!taskOwner)return;const now=new Date().toISOString();const todo={id:'todo-ar-'+Date.now(),title:taskTitle.trim(),description:'AR follow-up for '+selected.name,created_by:cu?.id,assigned_to:taskOwner,so_id:null,customer_id:selectedId,priority:1,status:'open',due_date:taskDue||null,created_at:now,updated_at:now,comments:[]};setAssignedTodos?.(prev=>[todo,...prev]);setTaskTitle('');setTaskDue('');saveWorkflow({status:taskOwner===selected.repId?'rep_action':'accounting_followup',next_action_date:taskDue||workflow.next_action_date||null});nf?.('AR action item assigned.','success')};
  const toggleTask=t=>{const done=t.status==='complete'||t.status==='completed';const now=new Date().toISOString();setAssignedTodos?.(prev=>prev.map(x=>x.id===t.id?{...x,status:done?'open':'complete',completed_at:done?null:now,completed_by:done?null:cu?.id,updated_at:now}:x))};
  const sendEmail=async()=>{const recipients=emailTo.split(/[;,]/).map(s=>s.trim()).filter(validEmail);if(!recipients.length){nf?.('Add a valid customer email address.','error');return}if(!emailSubject.trim()||!emailBody.trim()){nf?.('Subject and message are required.','error');return}setEmailSending(true);const inner='<div style="white-space:pre-wrap">'+esc(emailBody).replace(/\n/g,'<br/>')+'</div>';const staffEmail=/@nationalsportsapparel\.com$/i.test(cu?.email||'')?cu.email:'noreply@nationalsportsapparel.com';const result=await sendBrevoEmail({to:recipients.map(email=>({email})),subject:emailSubject.trim(),htmlContent:buildBrandedEmailHtml(inner,companyInfo),textContent:emailBody,senderName:cu?.name||'NSA Accounting',senderEmail:staffEmail,replyTo:cu?.email?{email:cu.email,name:cu.name}:undefined});setEmailSending(false);if(!result.ok){nf?.('Email failed: '+result.error,'error');return}const msg={id:'m'+Date.now(),so_id:null,author_id:cu?.id,text:'[AR EMAIL]\nTo: '+recipients.join(', ')+'\nSubject: '+emailSubject.trim()+'\n\n'+emailBody,ts:new Date().toLocaleString(),read_by:[cu?.id].filter(Boolean),dept:'accounting',tagged_members:[selected?.repId].filter(id=>id&&id!==cu?.id),entity_type:'customer',entity_id:selectedId};setMsgs?.(prev=>[...prev,msg]);const follow=new Date();follow.setDate(follow.getDate()+7);saveWorkflow({last_contacted_at:new Date().toISOString(),status:'waiting_customer',next_action_date:ymd(follow)});nf?.('Email sent and added to the account timeline.','success');setDrawerTab('timeline')};

  const timeline=useMemo(()=>[
    ...accountMessages.map(m=>({id:m.id,at:m.ts,type:m.text?.startsWith('[AR EMAIL]')?'email':'chat',author:REPS.find(r=>r.id===m.author_id)?.name||'Team',body:m.text})),
    ...inbound.map(m=>({id:m.id,at:m.received_at,type:'inbound',author:m.sender_name||m.sender_email,body:(m.subject?'Subject: '+m.subject+'\n':'')+(m.text_body||m.snippet||'')})),
    ...accountTasks.map(t=>({id:'task:'+t.id,at:t.updated_at||t.created_at,type:'task',author:REPS.find(r=>r.id===t.assigned_to)?.name||'Team',body:(t.status==='complete'||t.status==='completed'?'Completed: ':'Action item: ')+t.title+(t.due_date?' · due '+shortDate(t.due_date):'')})),
  ].sort((a,b)=>new Date(b.at)-new Date(a.at)),[accountMessages,inbound,accountTasks,REPS]);

  const orderedSnaps=[...snapshots].sort((a,b)=>String(a.as_of_date).localeCompare(String(b.as_of_date)));
  const previous=orderedSnaps.length>1?{...orderedSnaps[orderedSnaps.length-2],_date:orderedSnaps[orderedSnaps.length-2].as_of_date}:null;
  const currentSnapshot=snapshotRows.find(r=>r.scope_id===scopeId)||snapshotRows[0];
  const totalCompleted=exposure.reduce((a,r)=>a+r.completedUninvoiced,0),totalOrders=exposure.reduce((a,r)=>a+r.openOrderValue,0);
  const visibleCompletedOrders=completedOrders.filter(r=>{const q=orderSearch.trim().toLowerCase();return !q||((r.id||'')+' '+r.customerName+' '+(REPS.find(x=>x.id===r.repId)?.name||'')).toLowerCase().includes(q)});
  const completedTodoSources=new Set(assignedTodos.filter(t=>t.status==='open').map(t=>t.source));
  const openOrder=r=>{setESO?.(r.order);setESOC?.(cust.find(c=>c.id===r.customerId)||null);setPg?.('orders')};
  const incompleteSources=[['invoices','portal invoices'],['customer_invoices','NetSuite invoice history'],['sales_orders','sales orders'],['customers','customers']].filter(([key])=>_truncatedTables?.has?.(key)).map(([,label])=>label);

  return <div className="ar-workspace" style={{color:INK}}>
    <div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:12,marginBottom:12,flexWrap:'wrap'}}>
      <div><h2 style={{margin:0,fontFamily:FD,fontSize:24,color:NAVY,textTransform:'uppercase'}}>{mode==='report'?'My Receivables':'Accounts Receivable Operations'}</h2><div style={{fontSize:11.5,color:MUTED,maxWidth:760}}>One account-centered queue for balances, completed uninvoiced work, contact readiness, internal collaboration, customer email, and assigned follow-up.</div></div>
      <div style={{padding:'6px 10px',borderRadius:7,background:effectiveRep?'#eef2ff':'#f1f5f9',color:effectiveRep?BLUE:MUTED,fontSize:11,fontWeight:800}}>{effectiveRep?(REPS.find(r=>r.id===effectiveRep)?.name||'My accounts'):'All accounts'}</div>
    </div>
    {!!incompleteSources.length&&<div style={{background:'#fef3c7',border:'1px solid #f59e0b',borderRadius:8,color:'#92400e',padding:'9px 12px',fontSize:11.5,fontWeight:700,marginBottom:12}}>Report totals are incomplete: {incompleteSources.join(', ')} exceeded the row-load cap. Do not use these totals for collection decisions until the full data set is loaded.</div>}
    {!!ar.kpis.assumedHistoryCount&&<div role="alert" style={{background:'#fff7ed',border:'1px solid #f97316',borderRadius:8,color:'#9a3412',padding:'10px 12px',fontSize:11.5,marginBottom:12}}><b>NetSuite full-balance assumption is active.</b> {ar.kpis.assumedHistoryCount.toLocaleString()} NetSuite invoice row{ar.kpis.assumedHistoryCount===1?' is':'s are'} marked open without a current remaining balance, so their full {money(ar.kpis.assumedHistoryFaceValue)} original face value is included in Open AR, past due, forecasts, snapshots, exposure, and collection actions. Upload NetSuite <code>Amount Remaining</code> to replace these assumptions with exact balances.</div>}
    <div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:12}}>
      <Metric label="Open AR" value={money(ar.kpis.total)} sub={ar.openInvoices.length+' invoices · '+ar.kpis.assumedHistoryCount.toLocaleString()+' assumed full'} color={NAVY}/>
      <Metric label="Past due" value={money(ar.kpis.pastDue)} sub={pct(ar.kpis.pastDuePct)+' of AR'} color={ar.kpis.pastDue?RED:GOOD}/>
      <Metric label="Completed, uninvoiced" value={money(totalCompleted)} sub={completedOrders.length+' orders · view list ↓'} color={totalCompleted?AMBER:GOOD} onClick={()=>document.getElementById('completed-uninvoiced-orders')?.scrollIntoView({behavior:'smooth',block:'start'})}/>
      <Metric label="Other open orders" value={money(totalOrders)} sub="future account exposure" color={BLUE}/>
      <Metric label="7-day cash forecast" value={money(forecast.next7)} sub={forecast.qbLinked?forecast.qbLinked+' QB-linked invoices':'invoice behavior model'} color={GOOD}/>
      <Metric label="60-day cash forecast" value={money(forecast.forecast60)} sub={money(forecast.beyond60)+' remains at risk'} color={forecast.beyond60?AMBER:GOOD}/>
    </div>
    <div id="completed-uninvoiced-orders" style={{...card,padding:0,overflow:'hidden',marginBottom:12,borderTop:'4px solid '+(totalCompleted?AMBER:GOOD)}}>
      <div style={{padding:'13px 14px',borderBottom:'1px solid '+LINE,display:'flex',alignItems:'center',gap:10,flexWrap:'wrap',background:totalCompleted?'#fffaf2':'#f0fdf4'}}><div><h3 style={{margin:0,fontFamily:FD,fontSize:20,color:NAVY,textTransform:'uppercase'}}>Completed, uninvoiced orders</h3><div style={{fontSize:10.5,color:MUTED}}>This is the exact order list behind the {money(totalCompleted)} tile. Each order creates one deduplicated TODO for its assigned rep.</div></div><div style={{marginLeft:'auto',textAlign:'right'}}><div style={{fontFamily:FD,fontSize:24,fontWeight:800,color:totalCompleted?AMBER:GOOD}}>{completedOrders.length} order{completedOrders.length===1?'':'s'} · {money(totalCompleted)}</div><div style={{fontSize:10,color:MUTED}}>{completedOrders.filter(r=>completedTodoSources.has('completed_uninvoiced:'+r.id)).length} open rep TODO{completedOrders.length===1?'':'s'} synced</div></div><input aria-label="Search completed uninvoiced orders" value={orderSearch} onChange={e=>setOrderSearch(e.target.value)} placeholder="Search order, account, or rep…" style={{border:'1px solid '+LINE,borderRadius:7,padding:'7px 9px',fontSize:12,minWidth:230}}/></div>
      <div style={{overflowX:'auto',maxHeight:480}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1040}}><thead style={{position:'sticky',top:0,background:'#fff',zIndex:2}}><tr><th style={{...th,textAlign:'left'}}>Sales order</th><th style={{...th,textAlign:'left'}}>Account / rep</th><th style={{...th,textAlign:'left'}}>Completion status</th><th style={th}>Age</th><th style={th}>Order value</th><th style={th}>Already invoiced</th><th style={th}>Remaining to invoice</th><th style={{...th,textAlign:'left'}}>Rep TODO</th><th style={th}>Actions</th></tr></thead><tbody>{visibleCompletedOrders.map(r=>{const todoOpen=completedTodoSources.has('completed_uninvoiced:'+r.id);return <tr key={r.id} style={{background:r.ageDays>30?'#fffaf2':'#fff'}}><td style={{...td,textAlign:'left'}}><button onClick={()=>openOrder(r)} style={{border:0,background:'transparent',padding:0,color:BLUE,fontWeight:800,cursor:'pointer',fontSize:12}}>{r.id}</button>{r.memo&&<div title={r.memo} style={{fontSize:9.5,color:FAINT,maxWidth:190,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',marginTop:2}}>{r.memo}</div>}</td><td style={{...td,textAlign:'left'}}><b>{r.customerName}</b><div style={{fontSize:10,color:FAINT}}>{REPS.find(x=>x.id===r.repId)?.name||'Unassigned'}</div></td><td style={{...td,textAlign:'left'}}><span style={{display:'inline-block',padding:'2px 7px',borderRadius:9,background:'#fff7ed',color:AMBER,fontSize:10,fontWeight:800}}>{String(r.status||'complete').replaceAll('_',' ')}</span>{r.status!==r.storedStatus&&<div style={{fontSize:9,color:FAINT,marginTop:3}}>Stored: {String(r.storedStatus||'—').replaceAll('_',' ')}</div>}</td><td style={{...td,color:r.ageDays>30?RED:INK,fontWeight:r.ageDays>30?800:400}}>{r.ageDays==null?'—':r.ageDays+'d'}</td><td style={td}>{money(r.orderValue)}</td><td style={td}>{money(r.invoiced)}</td><td style={{...td,color:AMBER,fontWeight:900,fontSize:13}}>{money(r.openToInvoice)}</td><td style={{...td,textAlign:'left'}}>{r.repId?(todoOpen?<span style={{color:GOOD,fontWeight:800,fontSize:10.5}}>✓ Open on rep list</span>:<span style={{color:AMBER,fontWeight:800,fontSize:10.5}}>Syncing to rep…</span>):<span style={{color:RED,fontWeight:800,fontSize:10.5}}>Assign a rep</span>}</td><td style={td}><div style={{display:'flex',justifyContent:'flex-end',gap:5}}><button style={btn(true)} onClick={()=>openOrder(r)}>Open order</button>{r.customerId&&<button style={btn()} onClick={()=>{setSelectedId(r.customerId);setDrawerTab('timeline')}}>Account AR</button>}</div></td></tr>})}</tbody></table>{!visibleCompletedOrders.length&&<div style={{padding:26,textAlign:'center',color:MUTED}}>{completedOrders.length?'No completed orders match that search.':'No completed, uninvoiced orders in this scope.'}</div>}</div>
    </div>
    <div style={{...card,marginBottom:12}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',gap:12,flexWrap:'wrap'}}><div><h3 style={{margin:0,fontFamily:FD,fontSize:18,color:NAVY,textTransform:'uppercase'}}>Cash collection outlook</h3><div style={{fontSize:11,color:MUTED}}>Portal balances plus full-face-value fallback for NetSuite invoices marked open, adjusted by due date and observed payment speed. QB sync improves freshness; no bank connection is required.</div></div><div style={{fontSize:10.5,color:MUTED}}>QB-linked coverage: <b>{pct(forecast.qbCoveragePct)}</b></div></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(120px,1fr))',gap:8,marginTop:12}}>{[['Next 7 days',forecast.next7,GOOD],['Days 8–30',forecast.days8to30,BLUE],['Days 31–60',forecast.days31to60,AMBER],['Beyond 60 / risk',forecast.beyond60,RED]].map(([l,v,c])=><div key={l} style={{padding:10,borderRadius:8,background:c+'0d',border:'1px solid '+c+'33'}}><div style={{fontSize:10,fontWeight:800,textTransform:'uppercase',color:c}}>{l}</div><div style={{fontFamily:FD,fontSize:23,fontWeight:800,color:c}}>{money(v)}</div></div>)}</div>
    </div>
    <div style={{...card,marginBottom:12}}>
      <div style={{display:'flex',alignItems:'baseline',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h3 style={{margin:0,fontFamily:FD,fontSize:18,color:NAVY,textTransform:'uppercase'}}>Management trends</h3><div style={{fontSize:11,color:MUTED}}>An idempotent snapshot is saved once per day when this report opens.</div></div><span style={{fontSize:10.5,color:FAINT}}>{orderedSnaps.length} daily snapshot{orderedSnaps.length===1?'':'s'} retained</span></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(150px,1fr))',gap:8,marginTop:12}}><MiniTrend label="Open AR" current={currentSnapshot?.total_ar||0} previous={previous?Number(previous.total_ar):null} previousDate={previous?.as_of_date} color={NAVY}/><MiniTrend label="Past due" current={currentSnapshot?.past_due||0} previous={previous?Number(previous.past_due):null} previousDate={previous?.as_of_date} color={RED}/><MiniTrend label="60+" current={currentSnapshot?.d60plus||0} previous={previous?Number(previous.d60plus):null} previousDate={previous?.as_of_date} color={AMBER}/><MiniTrend label="Completed uninvoiced" current={currentSnapshot?.completed_uninvoiced||0} previous={previous?Number(previous.completed_uninvoiced):null} previousDate={previous?.as_of_date} color={BLUE}/></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(360px,1fr))',gap:12,marginBottom:12}}>
      <div style={card}><h3 style={{margin:'0 0 4px',fontFamily:FD,fontSize:18,color:NAVY,textTransform:'uppercase'}}>Average days to pay by rep</h3><div style={{fontSize:10.5,color:MUTED,marginBottom:8}}>Based only on portal invoices with an observable final-payment date.</div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{...th,textAlign:'left'}}>Rep</th><th style={th}>Average</th><th style={th}>Worst account</th><th style={th}>Samples</th></tr></thead><tbody>{ar.repPayRows.map(r=><tr key={r.repId}><td style={{...td,textAlign:'left',fontWeight:700}}>{r.name}</td><td style={td}>{r.avgDays==null?'—':Math.round(r.avgDays)+'d'}</td><td style={td}>{r.worstAccount?Math.round(r.worstAccount.avgDays)+'d avg · '+r.worstAccount.maxDays+'d worst':'—'}</td><td style={td}>{r.count||0}</td></tr>)}</tbody></table>{!ar.repPayRows.length&&<div style={{padding:14,textAlign:'center',color:MUTED,fontSize:11}}>No completed-payment history is available.</div>}</div></div>
      <div style={card}><h3 style={{margin:'0 0 4px',fontFamily:FD,fontSize:18,color:NAVY,textTransform:'uppercase'}}>Slowest-paying accounts</h3><div style={{fontSize:10.5,color:MUTED,marginBottom:8}}>Average and worst observed payment time for each account.</div><div style={{overflowX:'auto',maxHeight:260}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{...th,textAlign:'left'}}>Account</th><th style={th}>Average</th><th style={th}>Worst</th><th style={th}>Terms</th><th style={th}>Samples</th></tr></thead><tbody>{ar.accountPayRows.slice(0,40).map(r=><tr key={r.customerId}><td style={{...td,textAlign:'left',fontWeight:700}}>{r.name}</td><td style={td}>{Math.round(r.avgDays)}d</td><td style={{...td,color:r.maxDays>r.termsDays*2?RED:INK}}>{r.maxDays}d</td><td style={td}>{r.termsDays}d</td><td style={td}>{r.count}</td></tr>)}</tbody></table>{!ar.accountPayRows.length&&<div style={{padding:14,textAlign:'center',color:MUTED,fontSize:11}}>No completed-payment history is available.</div>}</div></div>
    </div>
    <div style={{...card,padding:0,overflow:'hidden'}}>
      <div style={{padding:'13px 14px',borderBottom:'1px solid '+LINE,display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'}}><div><b style={{fontFamily:FD,fontSize:18,color:NAVY,textTransform:'uppercase'}}>Collections & account-quality worklist</b><div style={{fontSize:9.5,color:FAINT}}>Open AR includes tax; uninvoiced order values are pre-tax estimates.</div></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search accounts…" style={{marginLeft:'auto',border:'1px solid '+LINE,borderRadius:7,padding:'7px 9px',fontSize:12,minWidth:210}}/>{[['needs_action','Needs action'],['past_due','Past due'],['60plus','60+'],['uninvoiced','Uninvoiced'],['data','Data issues'],['all','All']].map(([id,l])=><button key={id} style={btn(filter===id)} onClick={()=>setFilter(id)}>{l}</button>)}</div>
      <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1180}}><thead><tr><th style={{...th,textAlign:'left'}}>Account / rep</th><th style={th}>Open AR</th><th style={th}>Past due</th><th style={th}>Completed uninvoiced</th><th style={th}>Other orders</th><th style={th}>Total exposure*</th><th style={{...th,textAlign:'left'}}>Workflow</th><th style={{...th,textAlign:'left'}}>Contact readiness</th><th style={th}>Action</th></tr></thead><tbody>{visibleRows.slice(0,150).map(r=>{const w=r.workflow||{},sc=STATUS_COLOR[w.status||'needs_contact'];return <tr key={r.customerId||r.name} style={{background:r.d60plus?'#fffafb':'#fff'}}><td style={{...td,textAlign:'left'}}><b>{r.name}</b><div style={{fontSize:10.5,color:FAINT}}>{REPS.find(x=>x.id===r.repId)?.name||'Unassigned'}</div></td><td style={{...td,fontWeight:800}}>{money(r.openAR)}</td><td style={{...td,color:r.pastDue?RED:FAINT,fontWeight:r.pastDue?800:400}}>{money(r.pastDue)}</td><td style={{...td,color:r.completedUninvoiced?AMBER:FAINT,fontWeight:r.completedUninvoiced?800:400}}>{money(r.completedUninvoiced)}</td><td style={td}>{money(r.openOrderValue)}</td><td style={{...td,fontWeight:800,color:NAVY}}>{money(r.totalExposure)}</td><td style={{...td,textAlign:'left'}}><span style={{display:'inline-block',fontSize:10,fontWeight:800,color:sc,background:sc+'14',borderRadius:10,padding:'2px 7px'}}>{STATUS[w.status||'needs_contact']}</span><div style={{fontSize:10,color:w.next_action_date&&w.next_action_date<=ymd(today)?RED:FAINT,marginTop:3}}>{w.next_action_date?'Next '+shortDate(w.next_action_date):'No next action'}{w.collection_owner_id?' · '+(REPS.find(x=>x.id===w.collection_owner_id)?.name||'Owner'):''}</div></td><td style={{...td,textAlign:'left',maxWidth:260}}>{(r.issues||[]).length?(r.issues||[]).map(x=><span key={x} style={{display:'inline-block',fontSize:9.5,fontWeight:700,color:x.includes('billing')?RED:AMBER,background:x.includes('billing')?'#fef2f2':'#fffbeb',padding:'2px 6px',borderRadius:8,margin:'1px 3px 1px 0'}}>{x}</span>):<span style={{color:GOOD,fontSize:10.5,fontWeight:700}}>Contacts ready</span>}</td><td style={td}>{r.customerId?<button style={btn(true)} onClick={()=>setSelectedId(r.customerId)}>Open workspace</button>:<span style={{fontSize:10,color:FAINT}}>Link customer first</span>}</td></tr>})}</tbody></table>{!visibleRows.length&&<div style={{padding:28,textAlign:'center',color:MUTED}}>No accounts match this work queue.</div>}</div>
    </div>

    {selected&&<div style={{position:'fixed',inset:0,zIndex:120,background:'rgba(15,23,42,.34)'}} onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedId(null)}}><aside style={{position:'absolute',right:0,top:0,bottom:0,width:'min(760px,96vw)',background:'#fff',boxShadow:'-16px 0 44px rgba(15,23,42,.22)',overflowY:'auto'}}>
      <div style={{position:'sticky',top:0,zIndex:4,background:NAVY,color:'#fff',padding:'15px 18px'}}><div style={{display:'flex',alignItems:'flex-start',gap:12}}><div style={{flex:1}}><div style={{fontFamily:FD,fontWeight:800,fontSize:23,textTransform:'uppercase'}}>{selected.name}</div><div style={{fontSize:11,color:'#cbd5e1'}}>{rep?.name||'Unassigned rep'} · {money(selected.openAR)} open AR · {money(selected.totalExposure)} total exposure</div></div><button onClick={()=>setSelectedId(null)} style={{border:0,background:'rgba(255,255,255,.12)',color:'#fff',borderRadius:7,width:30,height:30,cursor:'pointer',fontSize:18}}>×</button></div><div style={{display:'flex',gap:4,marginTop:12,overflowX:'auto'}}>{[['timeline','Timeline & chat'],['workflow','Workflow'],['email','Email account'],['tasks','Action items'],['invoices','Invoices & exposure']].map(([id,l])=><button key={id} onClick={()=>setDrawerTab(id)} style={{border:'1px solid '+(drawerTab===id?'#fff':'rgba(255,255,255,.25)'),background:drawerTab===id?'#fff':'transparent',color:drawerTab===id?NAVY:'#fff',borderRadius:6,padding:'5px 9px',fontSize:10.5,fontWeight:800,cursor:'pointer',whiteSpace:'nowrap'}}>{l}</button>)}</div></div>
      <div style={{padding:16}}>
        <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(110px,1fr))',gap:7,marginBottom:14}}>{[['Open AR',selected.openAR,NAVY],['Past due',selected.pastDue,RED],['Ready to bill',selected.completedUninvoiced,AMBER],['Other orders',selected.openOrderValue,BLUE]].map(([l,v,c])=><div key={l} style={{padding:9,background:SURFACE,borderRadius:7,border:'1px solid '+LINE}}><div style={{fontSize:9.5,color:MUTED,textTransform:'uppercase',fontWeight:800}}>{l}</div><div style={{fontFamily:FD,fontSize:20,fontWeight:800,color:c}}>{money(v)}</div></div>)}</div>
        {drawerTab==='timeline'&&<><div style={{...card,marginBottom:12}}><div style={{fontWeight:800,color:NAVY,marginBottom:7}}>Internal AR conversation</div><textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder={'Message '+(rep?.name||'the assigned rep')+' and the AR team about this account…'} rows={3} style={{width:'100%',boxSizing:'border-box',border:'1px solid '+LINE,borderRadius:7,padding:9,font:'inherit',fontSize:12}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:7}}><span style={{fontSize:10,color:FAINT}}>The assigned rep and collection owner are notified.</span><button style={btn(true)} onClick={postChat}>Post message</button></div></div><div style={card}><div style={{fontWeight:800,color:NAVY,marginBottom:8}}>Account communication history</div>{timeline.length?timeline.map(x=>{const c=x.type==='email'?BLUE:x.type==='inbound'?GOOD:x.type==='task'?AMBER:NAVY;return <div key={x.id} style={{borderLeft:'3px solid '+c,padding:'7px 10px',marginBottom:8,background:c+'08',borderRadius:'0 7px 7px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b style={{fontSize:11,color:c}}>{x.type==='email'?'Email sent':x.type==='inbound'?'Customer email received':x.type==='task'?'Action item':'Internal chat'} · {x.author}</b><span style={{fontSize:9.5,color:FAINT}}>{shortDateTime(x.at)}</span></div><div style={{fontSize:11.5,color:INK,whiteSpace:'pre-wrap',marginTop:3,maxHeight:160,overflow:'auto'}}>{x.body}</div></div>}):<div style={{padding:22,textAlign:'center',color:MUTED}}>No AR communication has been recorded for this account yet.</div>}</div></>}
        {drawerTab==='workflow'&&<div style={card}><div style={{fontWeight:800,color:NAVY,marginBottom:12}}>Collection workflow</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label style={{fontSize:11,color:MUTED}}>Status<select value={workflow.status||'needs_contact'} onChange={e=>saveWorkflow({status:e.target.value})} style={{display:'block',width:'100%',marginTop:4,padding:8,border:'1px solid '+LINE,borderRadius:7}}>{Object.entries(STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={{fontSize:11,color:MUTED}}>Collection owner<select value={workflow.collection_owner_id||''} onChange={e=>saveWorkflow({collection_owner_id:e.target.value||null})} style={{display:'block',width:'100%',marginTop:4,padding:8,border:'1px solid '+LINE,borderRadius:7}}><option value="">Unassigned</option>{REPS.filter(r=>r.is_active!==false&&['admin','super_admin','gm','accounting','rep'].includes(r.role)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label style={{fontSize:11,color:MUTED}}>Next action date<input type="date" value={workflow.next_action_date||''} onChange={e=>saveWorkflow({next_action_date:e.target.value||null})} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:4,padding:8,border:'1px solid '+LINE,borderRadius:7}}/></label><label style={{fontSize:11,color:MUTED}}>Last contacted<input type="datetime-local" value={workflow.last_contacted_at?String(workflow.last_contacted_at).slice(0,16):''} onChange={e=>saveWorkflow({last_contacted_at:e.target.value?new Date(e.target.value).toISOString():null})} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:4,padding:8,border:'1px solid '+LINE,borderRadius:7}}/></label></div><label style={{display:'block',fontSize:11,color:MUTED,marginTop:10}}>Account AR notes<textarea value={workflow.notes||''} onChange={e=>setWorkflows(prev=>({...prev,[selectedId]:{...workflow,notes:e.target.value}}))} onBlur={e=>saveWorkflow({notes:e.target.value||null})} rows={6} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:4,padding:9,border:'1px solid '+LINE,borderRadius:7,font:'inherit'}}/></label><div style={{fontSize:10,color:FAINT,marginTop:8}}>Last contacted {shortDateTime(workflow.last_contacted_at)} · owner {owner?.name||'unassigned'}</div></div>}
        {drawerTab==='email'&&<div style={card}><div style={{fontWeight:800,color:NAVY}}>Email this account</div><div style={{fontSize:10.5,color:MUTED,margin:'3px 0 10px'}}>Billing contacts are selected first. Successful sends are recorded in the shared timeline and set a seven-day follow-up.</div><label style={{fontSize:11,color:MUTED}}>To<input value={emailTo} onChange={e=>setEmailTo(e.target.value)} placeholder="billing@example.com" style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:4,padding:8,border:'1px solid '+LINE,borderRadius:7}}/></label><label style={{display:'block',fontSize:11,color:MUTED,marginTop:9}}>Subject<input value={emailSubject} onChange={e=>setEmailSubject(e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:4,padding:8,border:'1px solid '+LINE,borderRadius:7}}/></label><label style={{display:'block',fontSize:11,color:MUTED,marginTop:9}}>Message<textarea value={emailBody} onChange={e=>setEmailBody(e.target.value)} rows={10} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:4,padding:9,border:'1px solid '+LINE,borderRadius:7,font:'inherit'}}/></label><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:10}}><span style={{fontSize:10,color:validEmail(emailTo)?GOOD:RED}}>{validEmail(emailTo)?'Ready to send':'A valid billing email is required'}</span><button style={{...btn(true),opacity:emailSending?.6:1}} disabled={emailSending} onClick={sendEmail}>{emailSending?'Sending…':'Send & log email'}</button></div></div>}
        {drawerTab==='tasks'&&<><div style={{...card,marginBottom:12}}><div style={{fontWeight:800,color:NAVY,marginBottom:8}}>Assign an AR action item</div><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="What needs to happen?" style={{width:'100%',boxSizing:'border-box',padding:8,border:'1px solid '+LINE,borderRadius:7,marginBottom:8}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:8}}><select value={taskOwner} onChange={e=>setTaskOwner(e.target.value)} style={{padding:8,border:'1px solid '+LINE,borderRadius:7}}><option value="">Assign to…</option>{REPS.filter(r=>r.is_active!==false).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input type="date" value={taskDue} onChange={e=>setTaskDue(e.target.value)} style={{padding:8,border:'1px solid '+LINE,borderRadius:7}}/><button style={btn(true)} onClick={addTask}>Assign</button></div></div><div style={card}>{accountTasks.length?accountTasks.map(t=>{const done=t.status==='complete'||t.status==='completed';return <div key={t.id} style={{display:'flex',alignItems:'flex-start',gap:9,padding:'8px 0',borderBottom:'1px solid '+LINE}}><input type="checkbox" checked={done} onChange={()=>toggleTask(t)} style={{marginTop:3}}/><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,textDecoration:done?'line-through':'none',color:done?FAINT:INK}}>{t.title}</div><div style={{fontSize:10,color:FAINT}}>{REPS.find(r=>r.id===t.assigned_to)?.name||'Unassigned'}{t.due_date?' · due '+shortDate(t.due_date):''}</div></div></div>}):<div style={{padding:18,textAlign:'center',color:MUTED}}>No account action items yet.</div>}</div></>}
        {drawerTab==='invoices'&&<><div style={{...card,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><b style={{color:NAVY}}>Exposure breakdown</b><button style={btn()} onClick={()=>{if(customer){setSelC?.(customer);setPg?.('customers')}}}>Open customer record</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8,marginTop:10}}>{[['Open invoices',selected.openAR],['Past due invoices',selected.pastDue],['Completed not invoiced',selected.completedUninvoiced],['Other open orders',selected.openOrderValue]].map(([l,v])=><div key={l} style={{padding:10,background:SURFACE,borderRadius:7}}><div style={{fontSize:10,color:MUTED}}>{l}</div><b style={{fontFamily:FD,fontSize:21,color:NAVY}}>{money(v)}</b></div>)}</div></div><div style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8}}><b style={{color:NAVY}}>Open invoices</b><button style={btn()} onClick={()=>{setInvF?.(f=>({...f,search:selected.name||'',status:'open',group:'list',aging:'all',rep:'all'}));setPg?.('invoices')}}>Open invoice report</button></div>{(selectedAr?.invoices||[]).map(i=><div key={i.source+':'+i.id} style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr 1fr',gap:8,padding:'8px 0',borderBottom:'1px solid '+LINE,fontSize:11}}><b>{i.id}</b><span>{shortDate(i.dueDate)}</span><span style={{color:i.daysPastDue?RED:GOOD}}>{i.daysPastDue?i.daysPastDue+'d late':'Current'}</span><b style={{textAlign:'right'}}>{money(i.balance)}</b></div>)}{!(selectedAr?.invoices||[]).length&&<div style={{padding:18,textAlign:'center',color:MUTED}}>No open invoices.</div>}</div></>}
      </div>
    </aside></div>}
  </div>;
}
