import React,{useRef,useState} from 'react';
import {authFetch} from './utils';

const labels={running:'Running — not verified',complete:'Clean read-only review',needs_review:'Needs review',failed:'Failed',abandoned:'Abandoned — not verified'};
export default function QBPayableServerReviewCard(){
  const[state,setState]=useState(null),[busy,setBusy]=useState(false),[waiting,setWaiting]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const baseline=useRef(null),inFlight=useRef(false);
  async function read(){const response=await authFetch('/.netlify/functions/qbo-payable-review-status',{method:'GET',cache:'no-store'});if(!response.ok)throw new Error('Cannot read payable review history.');const data=await response.json();if(!Array.isArray(data.runs)||data.mode!=='read_only')throw new Error('Server payable review is not deployed yet.');setState(data);if(baseline.current){const run=data.runs.find(item=>!baseline.current.has(item.id));if(run){setNotice('Durable payable review recorded: '+run.id+'.');baseline.current=null;setWaiting(false)}}return data}
  async function act(start){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{const data=await read();if(!start)return;if(!data.enabled||data.runs.some(run=>run.status==='running'))throw new Error('Review is disabled or already running.');baseline.current=new Set(data.runs.map(run=>run.id));setWaiting(true);setNotice('Request accepted; the server continues if this tab closes. Refresh history to verify the durable result.');const response=await authFetch('/.netlify/functions/qbo-payable-review-background',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw new Error('Request outcome is unverified. Refresh history before retrying.')}catch(e){setError(e.message||'Payable review unavailable')}finally{inFlight.current=false;setBusy(false)}}
  return <section aria-label="Server payable review">
    <p style={{fontSize:11,color:'#475569'}}>Runs against the authoritative Portal bill ledger and live QBO on the server, even after this tab closes. This is read-only; bill and vendor-credit creation remain disabled.</p>
    <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btn-secondary btn-sm" disabled={busy} onClick={()=>act(false)}>Refresh payable review history</button><button className="btn btn-sm" disabled={busy||waiting||!state?.enabled||state?.runs.some(run=>run.status==='running')} onClick={()=>act(true)}>Run Server Bill Review — No QBO Changes</button></div>
    {!state&&<p>Refresh history first to verify the server deployment and lock state.</p>}
    {state&&<p>Server review: {state.enabled?'enabled':'disabled'} · QBO realm: {state.realm||'not configured'}</p>}
    {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" style={{color:'#b91c1c'}}>{error}</p>}
    {state?.runs.map(run=><details key={run.id} style={{marginTop:10}}><summary>{run.started_at} · {labels[run.status]||'Unknown — not verified'} · {run.id}</summary><p>Finished: {run.finished_at||'not yet'} · Source rows: {run.report?.population??'not verified'} · Counts: {JSON.stringify(run.report?.counts||{})}</p>{run.report&&<><p>{run.report.sourceChanged?'Source changed during review — rerun required.':'Source snapshot stayed unchanged.'} Source hash: {run.report.sourceHash}</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Type</th><th>Vendor doc</th><th>Vendor</th><th>Date</th><th>Total</th><th>Result</th><th>Reason</th></tr></thead><tbody>{(run.report.results||[]).filter(row=>!['ready','already_exists'].includes(row.action)).slice(0,250).map(row=><tr key={row.ledgerId}><td>{row.transactionType}</td><td>{row.documentNumber}</td><td>{row.vendor}</td><td>{row.date||'—'}</td><td>${Number(row.total||0).toFixed(2)}</td><td>{row.action}</td><td>{row.reason}</td></tr>)}</tbody></table></div></>}</details>)}
    <p style={{fontSize:10,color:'#92400e'}}>A clean review is evidence only. It does not unlock or execute payable automation; a separate reviewed canary and explicit approval remain required.</p>
  </section>;
}
