import React,{useRef,useState} from 'react';
import {authFetch} from './utils';

const labels={running:'Running — not verified',complete:'Clean read-only review',needs_review:'Needs review',failed:'Failed',abandoned:'Abandoned — not verified'};
const money=value=>'$'+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
export default function QBPayableServerReviewCard(){
  const[state,setState]=useState(null),[busy,setBusy]=useState(false),[waiting,setWaiting]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const baseline=useRef(null),inFlight=useRef(false);
  async function read(){const response=await authFetch('/.netlify/functions/qbo-payable-review-status',{method:'GET',cache:'no-store'});if(!response.ok)throw new Error('Cannot read payable review history.');const data=await response.json();if(!Array.isArray(data.runs)||data.mode!=='read_only')throw new Error('Server payable review is not deployed yet.');setState(data);if(baseline.current){const run=data.runs.find(item=>!baseline.current.has(item.id));if(run){setNotice('Durable payable review recorded: '+run.id+'.');baseline.current=null;setWaiting(false)}}return data}
  async function act(start){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{const data=await read();if(!start)return;if(!data.enabled||data.runs.some(run=>run.status==='running'))throw new Error('Review is disabled or already running.');baseline.current=new Set(data.runs.map(run=>run.id));setWaiting(true);setNotice('Request accepted; the server continues if this tab closes. Refresh history to verify the durable result.');const response=await authFetch('/.netlify/functions/qbo-payable-review-background',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw new Error('Request outcome is unverified. Refresh history before retrying.')}catch(e){setError(e.message||'Payable review unavailable')}finally{inFlight.current=false;setBusy(false)}}
  return <section aria-label="Server payable review">
    <p style={{fontSize:11,color:'#475569'}}>Runs against the authoritative Portal PO and bill ledgers plus live QBO on the server, even after this tab closes. This is read-only; PO, bill, vendor-credit, vendor-payment, vendor and item creation remain disabled.</p>
    <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btn-secondary btn-sm" disabled={busy} onClick={()=>act(false)}>Refresh payable review history</button><button className="btn btn-sm" disabled={busy||waiting||!state?.enabled||state?.runs.some(run=>run.status==='running')} onClick={()=>act(true)}>Run Server Payable Review — No QBO Changes</button></div>
    {!state&&<p>Refresh history first to verify the server deployment and lock state.</p>}
    {state&&<p>Server review: {state.enabled?'enabled':'disabled'} · QBO realm: {state.realm||'not configured'}</p>}
    {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" style={{color:'#b91c1c'}}>{error}</p>}
    {state?.runs.map(run=><details key={run.id} style={{marginTop:10}}><summary>{run.started_at} · {labels[run.status]||'Unknown — not verified'} · {run.id}</summary><p>Finished: {run.finished_at||'not yet'} · Source bill rows: {run.report?.population??'not verified'} · Counts: {JSON.stringify(run.report?.counts||{})}</p>{run.report&&<><p>{run.report.sourceChanged?'Source changed during review — rerun required.':'Source snapshot stayed unchanged.'} Source hash: {run.report.sourceHash}</p>
      {run.report.totals&&<p><strong>Dollar totals:</strong> {Object.entries(run.report.totals).map(([key,value])=>key+' '+money(value)).join(' · ')}</p>}
      {run.report.ap&&<p><strong>A/P:</strong> before {money(run.report.ap.before?.net)} · after {money(run.report.ap.after?.net)} · delta {money(run.report.ap.delta)}{run.report.ap.changedDuringReview?' — changed while the review ran':' — unchanged during review'}</p>}
      <div style={{overflowX:'auto'}}><table><thead><tr><th>Type</th><th>Vendor doc</th><th>Vendor</th><th>Date</th><th>Total</th><th>Result</th><th>Reason</th></tr></thead><tbody>{(run.report.results||[]).filter(row=>!['ready','already_exists'].includes(row.action)).slice(0,250).map(row=><tr key={row.ledgerId}><td>{row.transactionType}</td><td>{row.documentNumber}</td><td>{row.vendor}</td><td>{row.date||'—'}</td><td>${Number(row.total||0).toFixed(2)}</td><td>{row.action}</td><td>{row.reason}</td></tr>)}</tbody></table></div>
      {!!run.report.purchaseOrders?.awaiting?.filter(row=>['blocked','conflict'].includes(row.action)).length&&<details><summary>PO exceptions</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.purchaseOrders.awaiting.filter(row=>['blocked','conflict'].includes(row.action)),null,2)}</pre></details>}
      {!!run.report.purchaseOrders?.unlinkedItems?.length&&<details><summary>Unlinked PO items ({run.report.purchaseOrders.unlinkedItems.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.purchaseOrders.unlinkedItems,null,2)}</pre></details>}
      {!!run.report.purchaseOrders?.invalidItemLinks?.length&&<details><summary>Invalid durable item links ({run.report.purchaseOrders.invalidItemLinks.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.purchaseOrders.invalidItemLinks,null,2)}</pre></details>}
      {!!run.report.unlinkedVendors?.length&&<details><summary>Unlinked or ambiguous vendors ({run.report.unlinkedVendors.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.unlinkedVendors,null,2)}</pre></details>}
      {!!run.report.vendorLinkSuggestions?.length&&<details><summary>Vendor links eligible for reviewed linking ({run.report.vendorLinkSuggestions.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.vendorLinkSuggestions,null,2)}</pre></details>}
      {!!run.report.purchaseOrders?.excluded?.length&&<details><summary>Excluded historical or parked POs ({run.report.purchaseOrders.excluded.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.purchaseOrders.excluded,null,2)}</pre></details>}
      {!!run.report.nativePOLinks?.exceptions?.length&&<details><summary>Native PO-to-bill exceptions ({run.report.nativePOLinks.exceptions.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.nativePOLinks.exceptions,null,2)}</pre></details>}
      {!!run.report.nativePOLinks?.verified?.length&&<details><summary>Verified native PO-to-bill links ({run.report.nativePOLinks.verified.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.nativePOLinks.verified,null,2)}</pre></details>}
      {!!run.report.payments?.missingApplications?.length&&<details><summary>Payments missing underlying bills ({run.report.payments.missingApplications.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.payments.missingApplications,null,2)}</pre></details>}
      {!!run.report.payments?.historicalPrintQueue?.length&&<details><summary>Historical payments queued for printing ({run.report.payments.historicalPrintQueue.length})</summary><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{JSON.stringify(run.report.payments.historicalPrintQueue,null,2)}</pre></details>}
      {!!run.report.missingAccounts?.length&&<p style={{color:'#b91c1c'}}><strong>Missing/invalid accounts:</strong> {run.report.missingAccounts.map(row=>row.number+' '+row.key+' — '+row.reason).join(', ')}</p>}
      <p style={{fontSize:10,color:'#166534'}}>QBO writes: {run.report.safeguards?.qboWrites??0} · Inventory quantities posted: {run.report.safeguards?.inventoryQuantitiesPosted?'yes':'no'} · Recurring payable automation enabled: {run.report.safeguards?.recurringAutomationEnabled?'yes':'no'}</p>
    </>}</details>)}
    <p style={{fontSize:10,color:'#92400e'}}>A clean review is evidence only. It does not unlock or execute payable automation; a separate reviewed canary and explicit approval remain required.</p>
  </section>;
}
