-- Standalone Methodic brand workflow.
--
-- This is intentionally linked to normal National sales orders and their art jobs;
-- it does not depend on the public custom-uniform builder tables. Staff browsers may
-- read the queues, while all lifecycle writes go through methodic-workflow.js so art
-- handoffs and audit events stay in one server-side transaction boundary.

create sequence if not exists public.methodic_request_number_seq start with 1001;

create table if not exists public.methodic_requests (
  id uuid primary key default gen_random_uuid(),
  request_number text not null unique default
    ('MTH-' || lpad(nextval('public.methodic_request_number_seq')::text, 5, '0')),
  sales_order_id text not null references public.sales_orders(id) on delete cascade,
  customer_id text references public.customers(id) on delete set null,
  rep_id text references public.team_members(id) on delete set null,
  art_job_id text,
  art_request_id text,

  title text not null,
  style_number text,
  garment_description text,
  garment_color text,
  quantity integer not null default 0 check (quantity >= 0),
  size_breakdown jsonb not null default '{}'::jsonb,
  request_notes text,
  reference_files jsonb not null default '[]'::jsonb,
  priority text not null default 'normal' check (priority in ('low','normal','high','rush')),
  owner_id text references public.team_members(id) on delete set null,
  blocker text,

  pricing_status text not null default 'not_requested' check (pricing_status in (
    'not_requested','requested','working','quoted','approved','declined','expired'
  )),
  pricing_requested_at timestamptz,
  expected_pricing_date date,
  quoted_at timestamptz,
  quoted_unit_cost_cents integer check (quoted_unit_cost_cents is null or quoted_unit_cost_cents >= 0),
  quoted_setup_cost_cents integer check (quoted_setup_cost_cents is null or quoted_setup_cost_cents >= 0),
  quote_expires_on date,
  pricing_notes text,

  mockup_status text not null default 'not_requested' check (mockup_status in (
    'not_requested','requested','in_art','ready_for_rep','revisions_requested','approved','cancelled'
  )),
  mockup_requested_at timestamptz,
  expected_mockup_date date,
  mockup_ready_at timestamptz,
  mockup_approved_at timestamptz,

  sample_status text not null default 'not_requested' check (sample_status in (
    'not_requested','requested','confirmed','in_production','shipped','received','approved','changes_requested','waived','cancelled'
  )),
  sample_requested_at timestamptz,
  expected_sample_date date,
  sample_tracking_number text,
  sample_tracking_url text,
  sample_received_at timestamptz,

  order_status text not null default 'not_ordered' check (order_status in (
    'not_ordered','po_needed','po_ready','ordered','confirmed','in_production','quality_check','shipped','delivered','on_hold','cancelled'
  )),
  purchase_order_id uuid references public.purchase_orders(id) on delete set null,
  purchase_order_number text,
  methodic_order_number text,
  ordered_at timestamptz,
  expected_ship_date date,
  expected_arrival_date date,
  carrier text,
  tracking_number text,
  tracking_url text,
  shipped_at timestamptz,
  delivered_at timestamptz,

  billing_status text not null default 'not_ready' check (billing_status in (
    'not_ready','ready','queued','posted','verified','error','void'
  )),
  methodic_invoice_number text,
  methodic_qb_transaction_id text,
  national_qb_transaction_id text,
  billing_error text,

  created_by text references public.team_members(id) on delete set null,
  updated_by text references public.team_members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint methodic_request_reference_files_array check (jsonb_typeof(reference_files) = 'array'),
  constraint methodic_request_size_breakdown_object check (jsonb_typeof(size_breakdown) = 'object')
);

create table if not exists public.methodic_request_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.methodic_requests(id) on delete cascade,
  event_type text not null,
  actor_id text references public.team_members(id) on delete set null,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint methodic_request_event_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create index if not exists methodic_requests_so_idx on public.methodic_requests (sales_order_id, updated_at desc);
create index if not exists methodic_requests_rep_idx on public.methodic_requests (rep_id, updated_at desc);
create index if not exists methodic_requests_pricing_queue_idx on public.methodic_requests (pricing_status, expected_pricing_date);
create index if not exists methodic_requests_mockup_queue_idx on public.methodic_requests (mockup_status, expected_mockup_date);
create index if not exists methodic_requests_sample_queue_idx on public.methodic_requests (sample_status, expected_sample_date);
create index if not exists methodic_requests_order_queue_idx on public.methodic_requests (order_status, expected_ship_date, expected_arrival_date);
create index if not exists methodic_request_events_request_idx on public.methodic_request_events (request_id, created_at desc);

create or replace function public.set_methodic_request_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists methodic_request_updated_at on public.methodic_requests;
create trigger methodic_request_updated_at
before update on public.methodic_requests
for each row execute function public.set_methodic_request_updated_at();

-- Art remains authoritative for mockup progress. When an artist moves the linked
-- job, Methodic updates automatically so reps do not have to reconcile two boards.
create schema if not exists private;

create or replace function private.sync_methodic_request_from_art_job()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mockup_status text;
begin
  v_mockup_status := case new.art_status
    when 'art_requested' then 'in_art'
    when 'art_in_progress' then 'in_art'
    when 'waiting_approval' then 'ready_for_rep'
    when 'production_files_needed' then 'approved'
    when 'order_dtf_transfers' then 'approved'
    when 'upload_emb_files' then 'approved'
    when 'art_complete' then 'approved'
    else null
  end;

  if v_mockup_status is not null then
    update public.methodic_requests
       set mockup_status = v_mockup_status,
           mockup_ready_at = case when v_mockup_status = 'ready_for_rep' then coalesce(mockup_ready_at, now()) else mockup_ready_at end,
           mockup_approved_at = case when v_mockup_status = 'approved' then coalesce(mockup_approved_at, now()) else mockup_approved_at end
     where sales_order_id = new.so_id
       and art_job_id = new.id
       and mockup_status not in ('cancelled');
  end if;
  return new;
end;
$$;

drop trigger if exists methodic_request_art_job_sync on public.so_jobs;
create trigger methodic_request_art_job_sync
after update of art_status on public.so_jobs
for each row
when (old.art_status is distinct from new.art_status)
execute function private.sync_methodic_request_from_art_job();

revoke all on function private.sync_methodic_request_from_art_job() from public, anon, authenticated;

alter table public.methodic_requests enable row level security;
alter table public.methodic_request_events enable row level security;

drop policy if exists methodic_requests_staff_read on public.methodic_requests;
create policy methodic_requests_staff_read on public.methodic_requests
for select to authenticated
using ((select public.is_team_member()));

drop policy if exists methodic_request_events_staff_read on public.methodic_request_events;
create policy methodic_request_events_staff_read on public.methodic_request_events
for select to authenticated
using ((select public.is_team_member()));

revoke all on public.methodic_requests from anon, authenticated;
revoke all on public.methodic_request_events from anon, authenticated;
grant select on public.methodic_requests to authenticated;
grant select on public.methodic_request_events to authenticated;
grant all on public.methodic_requests to service_role;
grant all on public.methodic_request_events to service_role;
grant usage, select on sequence public.methodic_request_number_seq to service_role;
grant usage, select on sequence public.methodic_request_events_id_seq to service_role;
